/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: typeinfo.c
  Source: typeinfo.idl
  Cyclone DDS: V0.8.0

*****************************************************************/
#include "dds/ddsi/ddsi_xt_typeinfo.h"

static const uint32_t DDS_XTypes_TypeIdentifier_ops [] =
{
  /* TypeIdentifier */
  DDS_OP_ADR | DDS_OP_TYPE_UNI | DDS_OP_SUBTYPE_1BY, offsetof (DDS_XTypes_TypeIdentifier, _d), 14u, (50u << 16u) + 4u,
  DDS_OP_JEQ | DDS_OP_TYPE_STU | 47 /* StringSTypeDefn */, 112, offsetof (DDS_XTypes_TypeIdentifier, _u.string_sdefn),
  DDS_OP_JEQ | DDS_OP_TYPE_STU | 44 /* StringSTypeDefn */, 114, offsetof (DDS_XTypes_TypeIdentifier, _u.string_sdefn),
  DDS_OP_JEQ | DDS_OP_TYPE_STU | 44 /* StringLTypeDefn */, 113, offsetof (DDS_XTypes_TypeIdentifier, _u.string_ldefn),
  DDS_OP_JEQ | DDS_OP_TYPE_STU | 41 /* StringLTypeDefn */, 115, offsetof (DDS_XTypes_TypeIdentifier, _u.string_ldefn),
  DDS_OP_JEQ | DDS_OP_TYPE_STU | 41 /* PlainSequenceSElemDefn */, 128, offsetof (DDS_XTypes_TypeIdentifier, _u.seq_sdefn),
  DDS_OP_JEQ | DDS_OP_TYPE_STU | 52 /* PlainSequenceLElemDefn */, 129, offsetof (DDS_XTypes_TypeIdentifier, _u.seq_ldefn),
  DDS_OP_JEQ | DDS_OP_TYPE_STU | 58 /* PlainArraySElemDefn */, 144, offsetof (DDS_XTypes_TypeIdentifier, _u.array_sdefn),
  DDS_OP_JEQ | DDS_OP_TYPE_STU | 64 /* PlainArrayLElemDefn */, 145, offsetof (DDS_XTypes_TypeIdentifier, _u.array_ldefn),
  DDS_OP_JEQ | DDS_OP_TYPE_STU | 70 /* PlainMapSTypeDefn */, 160, offsetof (DDS_XTypes_TypeIdentifier, _u.map_sdefn),
  DDS_OP_JEQ | DDS_OP_TYPE_STU | 81 /* PlainMapLTypeDefn */, 161, offsetof (DDS_XTypes_TypeIdentifier, _u.map_ldefn),
  DDS_OP_JEQ | DDS_OP_TYPE_STU | 92 /* StronglyConnectedComponentId */, 176, offsetof (DDS_XTypes_TypeIdentifier, _u.sc_component_id),
  DDS_OP_JEQ | DDS_OP_TYPE_ARR | 9, 242, offsetof (DDS_XTypes_TypeIdentifier, _u.equivalence_hash),
  DDS_OP_JEQ | DDS_OP_TYPE_ARR | 6, 241, offsetof (DDS_XTypes_TypeIdentifier, _u.equivalence_hash),
  DDS_OP_JEQ | DDS_OP_TYPE_STU | 107 /* ExtendedTypeDefn */, 0, offsetof (DDS_XTypes_TypeIdentifier, _u.extended_defn),
  DDS_OP_ADR | DDS_OP_TYPE_ARR | DDS_OP_SUBTYPE_1BY, 0u, 14u,
  DDS_OP_RTS,
  DDS_OP_RTS,

  /* StringSTypeDefn */
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (DDS_XTypes_StringSTypeDefn, bound),
  DDS_OP_RTS,

  /* StringLTypeDefn */
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (DDS_XTypes_StringLTypeDefn, bound),
  DDS_OP_RTS,

  /* PlainSequenceSElemDefn */
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_PlainSequenceSElemDefn, header), (3u << 16u) + 9u /* PlainCollectionHeader */,
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (DDS_XTypes_PlainSequenceSElemDefn, bound),
  DDS_OP_ADR | DDS_OP_TYPE_EXT | DDS_OP_FLAG_EXT, offsetof (DDS_XTypes_PlainSequenceSElemDefn, element_identifier), (3u << 16u) + 65474u /* TypeIdentifier */,
  DDS_OP_RTS,

  /* PlainCollectionHeader */
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (DDS_XTypes_PlainCollectionHeader, equiv_kind),
  DDS_OP_ADR | DDS_OP_TYPE_2BY, offsetof (DDS_XTypes_PlainCollectionHeader, element_flags),
  DDS_OP_RTS,

  /* PlainSequenceLElemDefn */
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_PlainSequenceLElemDefn, header), (3u << 16u) + 65531u /* PlainCollectionHeader */,
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (DDS_XTypes_PlainSequenceLElemDefn, bound),
  DDS_OP_ADR | DDS_OP_TYPE_EXT | DDS_OP_FLAG_EXT, offsetof (DDS_XTypes_PlainSequenceLElemDefn, element_identifier), (3u << 16u) + 65460u /* TypeIdentifier */,
  DDS_OP_RTS,

  /* PlainArraySElemDefn */
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_PlainArraySElemDefn, header), (3u << 16u) + 65522u /* PlainCollectionHeader */,
  DDS_OP_ADR | DDS_OP_TYPE_SEQ | DDS_OP_SUBTYPE_1BY, offsetof (DDS_XTypes_PlainArraySElemDefn, array_bound_seq),
  DDS_OP_ADR | DDS_OP_TYPE_EXT | DDS_OP_FLAG_EXT, offsetof (DDS_XTypes_PlainArraySElemDefn, element_identifier), (3u << 16u) + 65451u /* TypeIdentifier */,
  DDS_OP_RTS,

  /* PlainArrayLElemDefn */
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_PlainArrayLElemDefn, header), (3u << 16u) + 65513u /* PlainCollectionHeader */,
  DDS_OP_ADR | DDS_OP_TYPE_SEQ | DDS_OP_SUBTYPE_4BY, offsetof (DDS_XTypes_PlainArrayLElemDefn, array_bound_seq),
  DDS_OP_ADR | DDS_OP_TYPE_EXT | DDS_OP_FLAG_EXT, offsetof (DDS_XTypes_PlainArrayLElemDefn, element_identifier), (3u << 16u) + 65442u /* TypeIdentifier */,
  DDS_OP_RTS,

  /* PlainMapSTypeDefn */
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_PlainMapSTypeDefn, header), (3u << 16u) + 65504u /* PlainCollectionHeader */,
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (DDS_XTypes_PlainMapSTypeDefn, bound),
  DDS_OP_ADR | DDS_OP_TYPE_EXT | DDS_OP_FLAG_EXT, offsetof (DDS_XTypes_PlainMapSTypeDefn, element_identifier), (3u << 16u) + 65433u /* TypeIdentifier */,
  DDS_OP_ADR | DDS_OP_TYPE_2BY, offsetof (DDS_XTypes_PlainMapSTypeDefn, key_flags),
  DDS_OP_ADR | DDS_OP_TYPE_EXT | DDS_OP_FLAG_EXT, offsetof (DDS_XTypes_PlainMapSTypeDefn, key_identifier), (3u << 16u) + 65428u /* TypeIdentifier */,
  DDS_OP_RTS,

  /* PlainMapLTypeDefn */
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_PlainMapLTypeDefn, header), (3u << 16u) + 65490u /* PlainCollectionHeader */,
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (DDS_XTypes_PlainMapLTypeDefn, bound),
  DDS_OP_ADR | DDS_OP_TYPE_EXT | DDS_OP_FLAG_EXT, offsetof (DDS_XTypes_PlainMapLTypeDefn, element_identifier), (3u << 16u) + 65419u /* TypeIdentifier */,
  DDS_OP_ADR | DDS_OP_TYPE_2BY, offsetof (DDS_XTypes_PlainMapLTypeDefn, key_flags),
  DDS_OP_ADR | DDS_OP_TYPE_EXT | DDS_OP_FLAG_EXT, offsetof (DDS_XTypes_PlainMapLTypeDefn, key_identifier), (3u << 16u) + 65414u /* TypeIdentifier */,
  DDS_OP_RTS,

  /* StronglyConnectedComponentId */
  DDS_OP_DLC,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_StronglyConnectedComponentId, sc_component_id), (3u << 16u) + 8u /* TypeObjectHashId */,
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (DDS_XTypes_StronglyConnectedComponentId, scc_length),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (DDS_XTypes_StronglyConnectedComponentId, scc_index),
  DDS_OP_RTS,

  /* TypeObjectHashId */
  DDS_OP_ADR | DDS_OP_TYPE_UNI | DDS_OP_SUBTYPE_1BY, offsetof (DDS_XTypes_TypeObjectHashId, _d), 2u, (14u << 16u) + 4u,
  DDS_OP_JEQ | DDS_OP_TYPE_ARR | 6, 242, offsetof (DDS_XTypes_TypeObjectHashId, _u.hash),
  DDS_OP_JEQ | DDS_OP_TYPE_ARR | 3, 241, offsetof (DDS_XTypes_TypeObjectHashId, _u.hash),
  DDS_OP_ADR | DDS_OP_TYPE_ARR | DDS_OP_SUBTYPE_1BY, 0u, 14u,
  DDS_OP_RTS,
  DDS_OP_RTS,

  /* ExtendedTypeDefn */
  DDS_OP_PLC,
  DDS_OP_RTS,

  /* ExtendedAnnotationParameterValue */
  DDS_OP_PLC,
  DDS_OP_RTS,

  /* AnnotationParameterValue */
  DDS_OP_ADR | DDS_OP_TYPE_UNI | DDS_OP_SUBTYPE_1BY, offsetof (DDS_XTypes_AnnotationParameterValue, _d), 14u, (50u << 16u) + 4u,
  DDS_OP_JEQ | DDS_OP_TYPE_1BY | 0, 1, offsetof (DDS_XTypes_AnnotationParameterValue, _u.boolean_value),
  DDS_OP_JEQ | DDS_OP_TYPE_1BY | 0, 2, offsetof (DDS_XTypes_AnnotationParameterValue, _u.byte_value),
  DDS_OP_JEQ | DDS_OP_TYPE_2BY | 0, 3, offsetof (DDS_XTypes_AnnotationParameterValue, _u.int16_value),
  DDS_OP_JEQ | DDS_OP_TYPE_2BY | 0, 6, offsetof (DDS_XTypes_AnnotationParameterValue, _u.uint_16_value),
  DDS_OP_JEQ | DDS_OP_TYPE_4BY | 0, 4, offsetof (DDS_XTypes_AnnotationParameterValue, _u.int32_value),
  DDS_OP_JEQ | DDS_OP_TYPE_4BY | 0, 7, offsetof (DDS_XTypes_AnnotationParameterValue, _u.uint32_value),
  DDS_OP_JEQ | DDS_OP_TYPE_8BY | 0, 5, offsetof (DDS_XTypes_AnnotationParameterValue, _u.int64_value),
  DDS_OP_JEQ | DDS_OP_TYPE_8BY | 0, 8, offsetof (DDS_XTypes_AnnotationParameterValue, _u.uint64_value),
  DDS_OP_JEQ | DDS_OP_TYPE_4BY | 0, 9, offsetof (DDS_XTypes_AnnotationParameterValue, _u.float32_value),
  DDS_OP_JEQ | DDS_OP_TYPE_8BY | 0, 10, offsetof (DDS_XTypes_AnnotationParameterValue, _u.float64_value),
  DDS_OP_JEQ | DDS_OP_TYPE_1BY | 0, 16, offsetof (DDS_XTypes_AnnotationParameterValue, _u.char_value),
  DDS_OP_JEQ | DDS_OP_TYPE_4BY | 0, 64, offsetof (DDS_XTypes_AnnotationParameterValue, _u.enumerated_value),
  DDS_OP_JEQ | DDS_OP_TYPE_BST | 6, 32, offsetof (DDS_XTypes_AnnotationParameterValue, _u.string8_value),
  DDS_OP_JEQ | DDS_OP_TYPE_STU | 65491 /* ExtendedAnnotationParameterValue */, 0, offsetof (DDS_XTypes_AnnotationParameterValue, _u.extended_value),
  DDS_OP_ADR | DDS_OP_TYPE_BST, offsetof (DDS_XTypes_AnnotationParameterValue, _u.string8_value), 129u,
  DDS_OP_RTS,
  DDS_OP_RTS,

  /* AppliedAnnotationParameter */
  DDS_OP_DLC,
  DDS_OP_ADR | DDS_OP_TYPE_ARR | DDS_OP_SUBTYPE_1BY, offsetof (DDS_XTypes_AppliedAnnotationParameter, paramname_hash), 4u,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_AppliedAnnotationParameter, value), (3u << 16u) + 65481u /* AnnotationParameterValue */,
  DDS_OP_RTS,

  /* AppliedAnnotation */
  DDS_OP_DLC,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_AppliedAnnotation, annotation_typeid), (3u << 16u) + 65322u /* TypeIdentifier */,
  DDS_OP_ADR | DDS_OP_TYPE_SEQ | DDS_OP_SUBTYPE_STU, offsetof (DDS_XTypes_AppliedAnnotation, param_seq), sizeof (DDS_XTypes_AppliedAnnotationParameter), (4u << 16u) + 65524u /* AppliedAnnotationParameter */,
  DDS_OP_RTS,

  /* AppliedVerbatimAnnotation */
  DDS_OP_ADR | DDS_OP_TYPE_BST, offsetof (DDS_XTypes_AppliedVerbatimAnnotation, placement), 33u,
  DDS_OP_ADR | DDS_OP_TYPE_BST, offsetof (DDS_XTypes_AppliedVerbatimAnnotation, language), 33u,
  DDS_OP_ADR | DDS_OP_TYPE_STR, offsetof (DDS_XTypes_AppliedVerbatimAnnotation, text),
  DDS_OP_RTS,

  /* AppliedBuiltinMemberAnnotations */
  DDS_OP_DLC,
  DDS_OP_ADR | DDS_OP_TYPE_STR, offsetof (DDS_XTypes_AppliedBuiltinMemberAnnotations, unit),
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_AppliedBuiltinMemberAnnotations, min), (3u << 16u) + 65456u /* AnnotationParameterValue */,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_AppliedBuiltinMemberAnnotations, max), (3u << 16u) + 65453u /* AnnotationParameterValue */,
  DDS_OP_ADR | DDS_OP_TYPE_STR, offsetof (DDS_XTypes_AppliedBuiltinMemberAnnotations, hash_id),
  DDS_OP_RTS,

  /* CommonStructMember */
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (DDS_XTypes_CommonStructMember, member_id),
  DDS_OP_ADR | DDS_OP_TYPE_2BY, offsetof (DDS_XTypes_CommonStructMember, member_flags),
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_CommonStructMember, member_type_id), (3u << 16u) + 65289u /* TypeIdentifier */,
  DDS_OP_RTS,

  /* CompleteMemberDetail */
  DDS_OP_ADR | DDS_OP_TYPE_BST, offsetof (DDS_XTypes_CompleteMemberDetail, name), 257u,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_CompleteMemberDetail, ann_builtin), (3u << 16u) + 65513u /* AppliedBuiltinMemberAnnotations */,
  DDS_OP_ADR | DDS_OP_TYPE_SEQ | DDS_OP_SUBTYPE_STU, offsetof (DDS_XTypes_CompleteMemberDetail, ann_custom), sizeof (DDS_XTypes_AppliedAnnotation), (4u << 16u) + 65492u /* AppliedAnnotation */,
  DDS_OP_RTS,

  /* MinimalMemberDetail */
  DDS_OP_ADR | DDS_OP_TYPE_ARR | DDS_OP_SUBTYPE_1BY, offsetof (DDS_XTypes_MinimalMemberDetail, name_hash), 4u,
  DDS_OP_RTS,

  /* CompleteStructMember */
  DDS_OP_DLC,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_CompleteStructMember, common), (3u << 16u) + 65512u /* CommonStructMember */,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_CompleteStructMember, detail), (3u << 16u) + 65517u /* CompleteMemberDetail */,
  DDS_OP_RTS,

  /* MinimalStructMember */
  DDS_OP_DLC,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_MinimalStructMember, common), (3u << 16u) + 65504u /* CommonStructMember */,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_MinimalStructMember, detail), (3u << 16u) + 65520u /* MinimalMemberDetail */,
  DDS_OP_RTS,

  /* AppliedBuiltinTypeAnnotations */
  DDS_OP_DLC,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_AppliedBuiltinTypeAnnotations, verbatim), (3u << 16u) + 65475u /* AppliedVerbatimAnnotation */,
  DDS_OP_RTS,

  /* MinimalTypeDetail */
  DDS_OP_RTS,

  /* CompleteTypeDetail */
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_CompleteTypeDetail, ann_builtin), (3u << 16u) + 65530u /* AppliedBuiltinTypeAnnotations */,
  DDS_OP_ADR | DDS_OP_TYPE_SEQ | DDS_OP_SUBTYPE_STU, offsetof (DDS_XTypes_CompleteTypeDetail, ann_custom), sizeof (DDS_XTypes_AppliedAnnotation), (4u << 16u) + 65458u /* AppliedAnnotation */,
  DDS_OP_ADR | DDS_OP_TYPE_BST, offsetof (DDS_XTypes_CompleteTypeDetail, type_name), 257u,
  DDS_OP_RTS,

  /* CompleteStructHeader */
  DDS_OP_DLC,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_CompleteStructHeader, base_type), (3u << 16u) + 65236u /* TypeIdentifier */,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_CompleteStructHeader, detail), (3u << 16u) + 65521u /* CompleteTypeDetail */,
  DDS_OP_RTS,

  /* MinimalStructHeader */
  DDS_OP_DLC,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_MinimalStructHeader, base_type), (3u << 16u) + 65228u /* TypeIdentifier */,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_MinimalStructHeader, detail), (3u << 16u) + 65512u /* MinimalTypeDetail */,
  DDS_OP_RTS,

  /* CompleteStructType */
  DDS_OP_ADR | DDS_OP_TYPE_2BY, offsetof (DDS_XTypes_CompleteStructType, struct_flags),
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_CompleteStructType, header), (3u << 16u) + 65518u /* CompleteStructHeader */,
  DDS_OP_ADR | DDS_OP_TYPE_SEQ | DDS_OP_SUBTYPE_STU, offsetof (DDS_XTypes_CompleteStructType, member_seq), sizeof (DDS_XTypes_CompleteStructMember), (4u << 16u) + 65482u /* CompleteStructMember */,
  DDS_OP_RTS,

  /* MinimalStructType */
  DDS_OP_ADR | DDS_OP_TYPE_2BY, offsetof (DDS_XTypes_MinimalStructType, struct_flags),
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_MinimalStructType, header), (3u << 16u) + 65516u /* MinimalStructHeader */,
  DDS_OP_ADR | DDS_OP_TYPE_SEQ | DDS_OP_SUBTYPE_STU, offsetof (DDS_XTypes_MinimalStructType, member_seq), sizeof (DDS_XTypes_MinimalStructMember), (4u << 16u) + 65480u /* MinimalStructMember */,
  DDS_OP_RTS,

  /* CommonUnionMember */
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (DDS_XTypes_CommonUnionMember, member_id),
  DDS_OP_ADR | DDS_OP_TYPE_2BY, offsetof (DDS_XTypes_CommonUnionMember, member_flags),
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_CommonUnionMember, type_id), (3u << 16u) + 65197u /* TypeIdentifier */,
  DDS_OP_ADR | DDS_OP_TYPE_SEQ | DDS_OP_SUBTYPE_4BY | DDS_OP_FLAG_SGN, offsetof (DDS_XTypes_CommonUnionMember, label_seq),
  DDS_OP_RTS,

  /* CompleteUnionMember */
  DDS_OP_DLC,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_CompleteUnionMember, common), (3u << 16u) + 65525u /* CommonUnionMember */,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_CompleteUnionMember, detail), (3u << 16u) + 65438u /* CompleteMemberDetail */,
  DDS_OP_RTS,

  /* MinimalUnionMember */
  DDS_OP_DLC,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_MinimalUnionMember, common), (3u << 16u) + 65517u /* CommonUnionMember */,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_MinimalUnionMember, detail), (3u << 16u) + 65441u /* MinimalMemberDetail */,
  DDS_OP_RTS,

  /* CommonDiscriminatorMember */
  DDS_OP_ADR | DDS_OP_TYPE_2BY, offsetof (DDS_XTypes_CommonDiscriminatorMember, member_flags),
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_CommonDiscriminatorMember, type_id), (3u << 16u) + 65173u /* TypeIdentifier */,
  DDS_OP_RTS,

  /* CompleteDiscriminatorMember */
  DDS_OP_DLC,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_CompleteDiscriminatorMember, common), (3u << 16u) + 65529u /* CommonDiscriminatorMember */,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_CompleteDiscriminatorMember, ann_builtin), (3u << 16u) + 65447u /* AppliedBuiltinTypeAnnotations */,
  DDS_OP_ADR | DDS_OP_TYPE_SEQ | DDS_OP_SUBTYPE_STU, offsetof (DDS_XTypes_CompleteDiscriminatorMember, ann_custom), sizeof (DDS_XTypes_AppliedAnnotation), (4u << 16u) + 65375u /* AppliedAnnotation */,
  DDS_OP_RTS,

  /* MinimalDiscriminatorMember */
  DDS_OP_DLC,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_MinimalDiscriminatorMember, common), (3u << 16u) + 65517u /* CommonDiscriminatorMember */,
  DDS_OP_RTS,

  /* CompleteUnionHeader */
  DDS_OP_DLC,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_CompleteUnionHeader, detail), (3u << 16u) + 65439u /* CompleteTypeDetail */,
  DDS_OP_RTS,

  /* MinimalUnionHeader */
  DDS_OP_DLC,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_MinimalUnionHeader, detail), (3u << 16u) + 65433u /* MinimalTypeDetail */,
  DDS_OP_RTS,

  /* CompleteUnionType */
  DDS_OP_ADR | DDS_OP_TYPE_2BY, offsetof (DDS_XTypes_CompleteUnionType, union_flags),
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_CompleteUnionType, header), (3u << 16u) + 65524u /* CompleteUnionHeader */,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_CompleteUnionType, discriminator), (3u << 16u) + 65504u /* CompleteDiscriminatorMember */,
  DDS_OP_ADR | DDS_OP_TYPE_SEQ | DDS_OP_SUBTYPE_STU, offsetof (DDS_XTypes_CompleteUnionType, member_seq), sizeof (DDS_XTypes_CompleteUnionMember), (4u << 16u) + 65479u /* CompleteUnionMember */,
  DDS_OP_RTS,

  /* MinimalUnionType */
  DDS_OP_ADR | DDS_OP_TYPE_2BY, offsetof (DDS_XTypes_MinimalUnionType, union_flags),
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_MinimalUnionType, header), (3u << 16u) + 65516u /* MinimalUnionHeader */,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_MinimalUnionType, discriminator), (3u << 16u) + 65503u /* MinimalDiscriminatorMember */,
  DDS_OP_ADR | DDS_OP_TYPE_SEQ | DDS_OP_SUBTYPE_STU, offsetof (DDS_XTypes_MinimalUnionType, member_seq), sizeof (DDS_XTypes_MinimalUnionMember), (4u << 16u) + 65474u /* MinimalUnionMember */,
  DDS_OP_RTS,

  /* CommonAnnotationParameter */
  DDS_OP_ADR | DDS_OP_TYPE_2BY, offsetof (DDS_XTypes_CommonAnnotationParameter, member_flags),
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_CommonAnnotationParameter, member_type_id), (3u << 16u) + 65114u /* TypeIdentifier */,
  DDS_OP_RTS,

  /* CompleteAnnotationParameter */
  DDS_OP_DLC,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_CompleteAnnotationParameter, common), (3u << 16u) + 65529u /* CommonAnnotationParameter */,
  DDS_OP_ADR | DDS_OP_TYPE_BST, offsetof (DDS_XTypes_CompleteAnnotationParameter, name), 257u,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_CompleteAnnotationParameter, default_value), (3u << 16u) + 65257u /* AnnotationParameterValue */,
  DDS_OP_RTS,

  /* MinimalAnnotationParameter */
  DDS_OP_DLC,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_MinimalAnnotationParameter, common), (3u << 16u) + 65518u /* CommonAnnotationParameter */,
  DDS_OP_ADR | DDS_OP_TYPE_ARR | DDS_OP_SUBTYPE_1BY, offsetof (DDS_XTypes_MinimalAnnotationParameter, name_hash), 4u,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_MinimalAnnotationParameter, default_value), (3u << 16u) + 65246u /* AnnotationParameterValue */,
  DDS_OP_RTS,

  /* CompleteAnnotationHeader */
  DDS_OP_DLC,
  DDS_OP_ADR | DDS_OP_TYPE_BST, offsetof (DDS_XTypes_CompleteAnnotationHeader, annotation_name), 257u,
  DDS_OP_RTS,

  /* MinimalAnnotationHeader */
  DDS_OP_DLC,
  DDS_OP_RTS,

  /* CompleteAnnotationType */
  DDS_OP_ADR | DDS_OP_TYPE_2BY, offsetof (DDS_XTypes_CompleteAnnotationType, annotation_flag),
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_CompleteAnnotationType, header), (3u << 16u) + 65527u /* CompleteAnnotationHeader */,
  DDS_OP_ADR | DDS_OP_TYPE_SEQ | DDS_OP_SUBTYPE_STU, offsetof (DDS_XTypes_CompleteAnnotationType, member_seq), sizeof (DDS_XTypes_CompleteAnnotationParameter), (4u << 16u) + 65502u /* CompleteAnnotationParameter */,
  DDS_OP_RTS,

  /* MinimalAnnotationType */
  DDS_OP_ADR | DDS_OP_TYPE_2BY, offsetof (DDS_XTypes_MinimalAnnotationType, annotation_flag),
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_MinimalAnnotationType, header), (3u << 16u) + 65522u /* MinimalAnnotationHeader */,
  DDS_OP_ADR | DDS_OP_TYPE_SEQ | DDS_OP_SUBTYPE_STU, offsetof (DDS_XTypes_MinimalAnnotationType, member_seq), sizeof (DDS_XTypes_MinimalAnnotationParameter), (4u << 16u) + 65503u /* MinimalAnnotationParameter */,
  DDS_OP_RTS,

  /* CommonAliasBody */
  DDS_OP_ADR | DDS_OP_TYPE_2BY, offsetof (DDS_XTypes_CommonAliasBody, related_flags),
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_CommonAliasBody, related_type), (3u << 16u) + 65059u /* TypeIdentifier */,
  DDS_OP_RTS,

  /* CompleteAliasBody */
  DDS_OP_DLC,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_CompleteAliasBody, common), (3u << 16u) + 65529u /* CommonAliasBody */,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_CompleteAliasBody, ann_builtin), (3u << 16u) + 65282u /* AppliedBuiltinMemberAnnotations */,
  DDS_OP_ADR | DDS_OP_TYPE_SEQ | DDS_OP_SUBTYPE_STU, offsetof (DDS_XTypes_CompleteAliasBody, ann_custom), sizeof (DDS_XTypes_AppliedAnnotation), (4u << 16u) + 65261u /* AppliedAnnotation */,
  DDS_OP_RTS,

  /* MinimalAliasBody */
  DDS_OP_DLC,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_MinimalAliasBody, common), (3u << 16u) + 65517u /* CommonAliasBody */,
  DDS_OP_RTS,

  /* CompleteAliasHeader */
  DDS_OP_DLC,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_CompleteAliasHeader, detail), (3u << 16u) + 65325u /* CompleteTypeDetail */,
  DDS_OP_RTS,

  /* MinimalAliasHeader */
  DDS_OP_DLC,
  DDS_OP_RTS,

  /* CompleteAliasType */
  DDS_OP_ADR | DDS_OP_TYPE_2BY, offsetof (DDS_XTypes_CompleteAliasType, alias_flags),
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_CompleteAliasType, header), (3u << 16u) + 65527u /* CompleteAliasHeader */,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_CompleteAliasType, body), (3u << 16u) + 65507u /* CompleteAliasBody */,
  DDS_OP_RTS,

  /* MinimalAliasType */
  DDS_OP_ADR | DDS_OP_TYPE_2BY, offsetof (DDS_XTypes_MinimalAliasType, alias_flags),
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_MinimalAliasType, header), (3u << 16u) + 65523u /* MinimalAliasHeader */,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_MinimalAliasType, body), (3u << 16u) + 65510u /* MinimalAliasBody */,
  DDS_OP_RTS,

  /* CompleteElementDetail */
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_CompleteElementDetail, ann_builtin), (3u << 16u) + 65244u /* AppliedBuiltinMemberAnnotations */,
  DDS_OP_ADR | DDS_OP_TYPE_SEQ | DDS_OP_SUBTYPE_STU, offsetof (DDS_XTypes_CompleteElementDetail, ann_custom), sizeof (DDS_XTypes_AppliedAnnotation), (4u << 16u) + 65223u /* AppliedAnnotation */,
  DDS_OP_RTS,

  /* CommonCollectionElement */
  DDS_OP_ADR | DDS_OP_TYPE_2BY, offsetof (DDS_XTypes_CommonCollectionElement, element_flags),
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_CommonCollectionElement, type), (3u << 16u) + 65003u /* TypeIdentifier */,
  DDS_OP_RTS,

  /* CompleteCollectionElement */
  DDS_OP_DLC,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_CompleteCollectionElement, common), (3u << 16u) + 65529u /* CommonCollectionElement */,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_CompleteCollectionElement, detail), (3u << 16u) + 65518u /* CompleteElementDetail */,
  DDS_OP_RTS,

  /* MinimalCollectionElement */
  DDS_OP_DLC,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_MinimalCollectionElement, common), (3u << 16u) + 65521u /* CommonCollectionElement */,
  DDS_OP_RTS,

  /* CommonCollectionHeader */
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (DDS_XTypes_CommonCollectionHeader, bound),
  DDS_OP_RTS,

  /* CompleteCollectionHeader */
  DDS_OP_DLC,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_CompleteCollectionHeader, common), (3u << 16u) + 65532u /* CommonCollectionHeader */,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_CompleteCollectionHeader, detail), (3u << 16u) + 65267u /* CompleteTypeDetail */,
  DDS_OP_RTS,

  /* MinimalCollectionHeader */
  DDS_OP_DLC,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_MinimalCollectionHeader, common), (3u << 16u) + 65524u /* CommonCollectionHeader */,
  DDS_OP_RTS,

  /* CompleteSequenceType */
  DDS_OP_ADR | DDS_OP_TYPE_2BY, offsetof (DDS_XTypes_CompleteSequenceType, collection_flag),
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_CompleteSequenceType, header), (3u << 16u) + 65521u /* CompleteCollectionHeader */,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_CompleteSequenceType, element), (3u << 16u) + 65502u /* CompleteCollectionElement */,
  DDS_OP_RTS,

  /* MinimalSequenceType */
  DDS_OP_ADR | DDS_OP_TYPE_2BY, offsetof (DDS_XTypes_MinimalSequenceType, collection_flag),
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_MinimalSequenceType, header), (3u << 16u) + 65520u /* MinimalCollectionHeader */,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_MinimalSequenceType, element), (3u << 16u) + 65501u /* MinimalCollectionElement */,
  DDS_OP_RTS,

  /* CommonArrayHeader */
  DDS_OP_ADR | DDS_OP_TYPE_SEQ | DDS_OP_SUBTYPE_4BY, offsetof (DDS_XTypes_CommonArrayHeader, bound_seq),
  DDS_OP_RTS,

  /* CompleteArrayHeader */
  DDS_OP_DLC,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_CompleteArrayHeader, common), (3u << 16u) + 65532u /* CommonArrayHeader */,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_CompleteArrayHeader, detail), (3u << 16u) + 65233u /* CompleteTypeDetail */,
  DDS_OP_RTS,

  /* MinimalArrayHeader */
  DDS_OP_DLC,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_MinimalArrayHeader, common), (3u << 16u) + 65524u /* CommonArrayHeader */,
  DDS_OP_RTS,

  /* CompleteArrayType */
  DDS_OP_DLC,
  DDS_OP_ADR | DDS_OP_TYPE_2BY, offsetof (DDS_XTypes_CompleteArrayType, collection_flag),
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_CompleteArrayType, header), (3u << 16u) + 65520u /* CompleteArrayHeader */,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_CompleteArrayType, element), (3u << 16u) + 65467u /* CompleteCollectionElement */,
  DDS_OP_RTS,

  /* MinimalArrayType */
  DDS_OP_ADR | DDS_OP_TYPE_2BY, offsetof (DDS_XTypes_MinimalArrayType, collection_flag),
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_MinimalArrayType, header), (3u << 16u) + 65519u /* MinimalArrayHeader */,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_MinimalArrayType, element), (3u << 16u) + 65466u /* MinimalCollectionElement */,
  DDS_OP_RTS,

  /* CompleteMapType */
  DDS_OP_ADR | DDS_OP_TYPE_2BY, offsetof (DDS_XTypes_CompleteMapType, collection_flag),
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_CompleteMapType, header), (3u << 16u) + 65468u /* CompleteCollectionHeader */,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_CompleteMapType, key), (3u << 16u) + 65449u /* CompleteCollectionElement */,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_CompleteMapType, element), (3u << 16u) + 65446u /* CompleteCollectionElement */,
  DDS_OP_RTS,

  /* MinimalMapType */
  DDS_OP_ADR | DDS_OP_TYPE_2BY, offsetof (DDS_XTypes_MinimalMapType, collection_flag),
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_MinimalMapType, header), (3u << 16u) + 65464u /* MinimalCollectionHeader */,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_MinimalMapType, key), (3u << 16u) + 65445u /* MinimalCollectionElement */,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_MinimalMapType, element), (3u << 16u) + 65442u /* MinimalCollectionElement */,
  DDS_OP_RTS,

  /* CommonEnumeratedLiteral */
  DDS_OP_DLC,
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (DDS_XTypes_CommonEnumeratedLiteral, value),
  DDS_OP_ADR | DDS_OP_TYPE_2BY, offsetof (DDS_XTypes_CommonEnumeratedLiteral, flags),
  DDS_OP_RTS,

  /* CompleteEnumeratedLiteral */
  DDS_OP_DLC,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_CompleteEnumeratedLiteral, common), (3u << 16u) + 65529u /* CommonEnumeratedLiteral */,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_CompleteEnumeratedLiteral, detail), (3u << 16u) + 65134u /* CompleteMemberDetail */,
  DDS_OP_RTS,

  /* MinimalEnumeratedLiteral */
  DDS_OP_DLC,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_MinimalEnumeratedLiteral, common), (3u << 16u) + 65521u /* CommonEnumeratedLiteral */,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_MinimalEnumeratedLiteral, detail), (3u << 16u) + 65137u /* MinimalMemberDetail */,
  DDS_OP_RTS,

  /* CommonEnumeratedHeader */
  DDS_OP_ADR | DDS_OP_TYPE_2BY, offsetof (DDS_XTypes_CommonEnumeratedHeader, bit_bound),
  DDS_OP_RTS,

  /* CompleteEnumeratedHeader */
  DDS_OP_DLC,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_CompleteEnumeratedHeader, common), (3u << 16u) + 65532u /* CommonEnumeratedHeader */,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_CompleteEnumeratedHeader, detail), (3u << 16u) + 65152u /* CompleteTypeDetail */,
  DDS_OP_RTS,

  /* MinimalEnumeratedHeader */
  DDS_OP_DLC,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_MinimalEnumeratedHeader, common), (3u << 16u) + 65524u /* CommonEnumeratedHeader */,
  DDS_OP_RTS,

  /* CompleteEnumeratedType */
  DDS_OP_ADR | DDS_OP_TYPE_2BY, offsetof (DDS_XTypes_CompleteEnumeratedType, enum_flags),
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_CompleteEnumeratedType, header), (3u << 16u) + 65521u /* CompleteEnumeratedHeader */,
  DDS_OP_ADR | DDS_OP_TYPE_SEQ | DDS_OP_SUBTYPE_STU, offsetof (DDS_XTypes_CompleteEnumeratedType, literal_seq), sizeof (DDS_XTypes_CompleteEnumeratedLiteral), (4u << 16u) + 65499u /* CompleteEnumeratedLiteral */,
  DDS_OP_RTS,

  /* MinimalEnumeratedType */
  DDS_OP_ADR | DDS_OP_TYPE_2BY, offsetof (DDS_XTypes_MinimalEnumeratedType, enum_flags),
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_MinimalEnumeratedType, header), (3u << 16u) + 65519u /* MinimalEnumeratedHeader */,
  DDS_OP_ADR | DDS_OP_TYPE_SEQ | DDS_OP_SUBTYPE_STU, offsetof (DDS_XTypes_MinimalEnumeratedType, literal_seq), sizeof (DDS_XTypes_MinimalEnumeratedLiteral), (4u << 16u) + 65497u /* MinimalEnumeratedLiteral */,
  DDS_OP_RTS,

  /* CommonBitflag */
  DDS_OP_ADR | DDS_OP_TYPE_2BY, offsetof (DDS_XTypes_CommonBitflag, position),
  DDS_OP_ADR | DDS_OP_TYPE_2BY, offsetof (DDS_XTypes_CommonBitflag, flags),
  DDS_OP_RTS,

  /* CompleteBitflag */
  DDS_OP_DLC,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_CompleteBitflag, common), (3u << 16u) + 65530u /* CommonBitflag */,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_CompleteBitflag, detail), (3u << 16u) + 65077u /* CompleteMemberDetail */,
  DDS_OP_RTS,

  /* MinimalBitflag */
  DDS_OP_DLC,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_MinimalBitflag, common), (3u << 16u) + 65522u /* CommonBitflag */,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_MinimalBitflag, detail), (3u << 16u) + 65080u /* MinimalMemberDetail */,
  DDS_OP_RTS,

  /* CompleteBitmaskType */
  DDS_OP_DLC,
  DDS_OP_ADR | DDS_OP_TYPE_2BY, offsetof (DDS_XTypes_CompleteBitmaskType, bitmask_flags),
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_CompleteBitmaskType, header), (3u << 16u) + 65476u /* CompleteEnumeratedHeader */,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, 0u, (3u << 16u) + 65473u /* CompleteEnumeratedHeader */,
  DDS_OP_ADR | DDS_OP_TYPE_SEQ | DDS_OP_SUBTYPE_STU, offsetof (DDS_XTypes_CompleteBitmaskType, flag_seq), sizeof (DDS_XTypes_CompleteBitflag), (4u << 16u) + 65508u /* CompleteBitflag */,
  DDS_OP_RTS,

  /* MinimalBitmaskType */
  DDS_OP_DLC,
  DDS_OP_ADR | DDS_OP_TYPE_2BY, offsetof (DDS_XTypes_MinimalBitmaskType, bitmask_flags),
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_MinimalBitmaskType, header), (3u << 16u) + 65470u /* MinimalEnumeratedHeader */,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, 0u, (3u << 16u) + 65467u /* MinimalEnumeratedHeader */,
  DDS_OP_ADR | DDS_OP_TYPE_SEQ | DDS_OP_SUBTYPE_STU, offsetof (DDS_XTypes_MinimalBitmaskType, flag_seq), sizeof (DDS_XTypes_MinimalBitflag), (4u << 16u) + 65502u /* MinimalBitflag */,
  DDS_OP_RTS,

  /* CommonBitfield */
  DDS_OP_ADR | DDS_OP_TYPE_2BY, offsetof (DDS_XTypes_CommonBitfield, position),
  DDS_OP_ADR | DDS_OP_TYPE_2BY, offsetof (DDS_XTypes_CommonBitfield, flags),
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (DDS_XTypes_CommonBitfield, bitcount),
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (DDS_XTypes_CommonBitfield, holder_type),
  DDS_OP_RTS,

  /* CompleteBitfield */
  DDS_OP_DLC,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_CompleteBitfield, common), (3u << 16u) + 65526u /* CommonBitfield */,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_CompleteBitfield, detail), (3u << 16u) + 65021u /* CompleteMemberDetail */,
  DDS_OP_RTS,

  /* MinimalBitfield */
  DDS_OP_DLC,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_MinimalBitfield, common), (3u << 16u) + 65518u /* CommonBitfield */,
  DDS_OP_ADR | DDS_OP_TYPE_ARR | DDS_OP_SUBTYPE_1BY, offsetof (DDS_XTypes_MinimalBitfield, name_hash), 4u,
  DDS_OP_RTS,

  /* CompleteBitsetHeader */
  DDS_OP_DLC,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_CompleteBitsetHeader, detail), (3u << 16u) + 65045u /* CompleteTypeDetail */,
  DDS_OP_RTS,

  /* MinimalBitsetHeader */
  DDS_OP_DLC,
  DDS_OP_RTS,

  /* CompleteBitsetType */
  DDS_OP_DLC,
  DDS_OP_ADR | DDS_OP_TYPE_2BY, offsetof (DDS_XTypes_CompleteBitsetType, bitset_flags),
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_CompleteBitsetType, header), (3u << 16u) + 65526u /* CompleteBitsetHeader */,
  DDS_OP_ADR | DDS_OP_TYPE_SEQ | DDS_OP_SUBTYPE_STU, offsetof (DDS_XTypes_CompleteBitsetType, field_seq), sizeof (DDS_XTypes_CompleteBitfield), (4u << 16u) + 65507u /* CompleteBitfield */,
  DDS_OP_RTS,

  /* MinimalBitsetType */
  DDS_OP_DLC,
  DDS_OP_ADR | DDS_OP_TYPE_2BY, offsetof (DDS_XTypes_MinimalBitsetType, bitset_flags),
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_MinimalBitsetType, header), (3u << 16u) + 65520u /* MinimalBitsetHeader */,
  DDS_OP_ADR | DDS_OP_TYPE_SEQ | DDS_OP_SUBTYPE_STU, offsetof (DDS_XTypes_MinimalBitsetType, field_seq), sizeof (DDS_XTypes_MinimalBitfield), (4u << 16u) + 65504u /* MinimalBitfield */,
  DDS_OP_RTS,

  /* CompleteExtendedType */
  DDS_OP_PLC,
  DDS_OP_RTS,

  /* CompleteTypeObject */
  DDS_OP_ADR | DDS_OP_TYPE_UNI | DDS_OP_SUBTYPE_1BY, offsetof (DDS_XTypes_CompleteTypeObject, _d), 11u, (37u << 16u) + 4u,
  DDS_OP_JEQ | DDS_OP_TYPE_STU | 65228 /* CompleteAliasType */, 48, offsetof (DDS_XTypes_CompleteTypeObject, _u.alias_type),
  DDS_OP_JEQ | DDS_OP_TYPE_STU | 65175 /* CompleteAnnotationType */, 80, offsetof (DDS_XTypes_CompleteTypeObject, _u.annotation_type),
  DDS_OP_JEQ | DDS_OP_TYPE_STU | 65032 /* CompleteStructType */, 81, offsetof (DDS_XTypes_CompleteTypeObject, _u.struct_type),
  DDS_OP_JEQ | DDS_OP_TYPE_STU | 65108 /* CompleteUnionType */, 82, offsetof (DDS_XTypes_CompleteTypeObject, _u.union_type),
  DDS_OP_JEQ | DDS_OP_TYPE_STU | 65496 /* CompleteBitsetType */, 83, offsetof (DDS_XTypes_CompleteTypeObject, _u.bitset_type),
  DDS_OP_JEQ | DDS_OP_TYPE_STU | 65274 /* CompleteSequenceType */, 96, offsetof (DDS_XTypes_CompleteTypeObject, _u.sequence_type),
  DDS_OP_JEQ | DDS_OP_TYPE_STU | 65305 /* CompleteArrayType */, 97, offsetof (DDS_XTypes_CompleteTypeObject, _u.array_type),
  DDS_OP_JEQ | DDS_OP_TYPE_STU | 65321 /* CompleteMapType */, 98, offsetof (DDS_XTypes_CompleteTypeObject, _u.map_type),
  DDS_OP_JEQ | DDS_OP_TYPE_STU | 65380 /* CompleteEnumeratedType */, 64, offsetof (DDS_XTypes_CompleteTypeObject, _u.enumerated_type),
  DDS_OP_JEQ | DDS_OP_TYPE_STU | 65421 /* CompleteBitmaskType */, 65, offsetof (DDS_XTypes_CompleteTypeObject, _u.bitmask_type),
  DDS_OP_JEQ | DDS_OP_TYPE_STU | 65500 /* CompleteExtendedType */, 0, offsetof (DDS_XTypes_CompleteTypeObject, _u.extended_type),
  DDS_OP_RTS,

  /* MinimalExtendedType */
  DDS_OP_PLC,
  DDS_OP_RTS,

  /* MinimalTypeObject */
  DDS_OP_ADR | DDS_OP_TYPE_UNI | DDS_OP_SUBTYPE_1BY, offsetof (DDS_XTypes_MinimalTypeObject, _d), 11u, (37u << 16u) + 4u,
  DDS_OP_JEQ | DDS_OP_TYPE_STU | 65197 /* MinimalAliasType */, 48, offsetof (DDS_XTypes_MinimalTypeObject, _u.alias_type),
  DDS_OP_JEQ | DDS_OP_TYPE_STU | 65145 /* MinimalAnnotationType */, 80, offsetof (DDS_XTypes_MinimalTypeObject, _u.annotation_type),
  DDS_OP_JEQ | DDS_OP_TYPE_STU | 65002 /* MinimalStructType */, 81, offsetof (DDS_XTypes_MinimalTypeObject, _u.struct_type),
  DDS_OP_JEQ | DDS_OP_TYPE_STU | 65081 /* MinimalUnionType */, 82, offsetof (DDS_XTypes_MinimalTypeObject, _u.union_type),
  DDS_OP_JEQ | DDS_OP_TYPE_STU | 65467 /* MinimalBitsetType */, 83, offsetof (DDS_XTypes_MinimalTypeObject, _u.bitset_type),
  DDS_OP_JEQ | DDS_OP_TYPE_STU | 65243 /* MinimalSequenceType */, 96, offsetof (DDS_XTypes_MinimalTypeObject, _u.sequence_type),
  DDS_OP_JEQ | DDS_OP_TYPE_STU | 65275 /* MinimalArrayType */, 97, offsetof (DDS_XTypes_MinimalTypeObject, _u.array_type),
  DDS_OP_JEQ | DDS_OP_TYPE_STU | 65293 /* MinimalMapType */, 98, offsetof (DDS_XTypes_MinimalTypeObject, _u.map_type),
  DDS_OP_JEQ | DDS_OP_TYPE_STU | 65350 /* MinimalEnumeratedType */, 64, offsetof (DDS_XTypes_MinimalTypeObject, _u.enumerated_type),
  DDS_OP_JEQ | DDS_OP_TYPE_STU | 65395 /* MinimalBitmaskType */, 65, offsetof (DDS_XTypes_MinimalTypeObject, _u.bitmask_type),
  DDS_OP_JEQ | DDS_OP_TYPE_STU | 65500 /* MinimalExtendedType */, 0, offsetof (DDS_XTypes_MinimalTypeObject, _u.extended_type),
  DDS_OP_RTS,

  /* TypeObject */
  DDS_OP_DLC,
  DDS_OP_ADR | DDS_OP_TYPE_UNI | DDS_OP_SUBTYPE_1BY, offsetof (DDS_XTypes_TypeObject, _d), 2u, (10u << 16u) + 4u,
  DDS_OP_JEQ | DDS_OP_TYPE_UNI | 65453 /* CompleteTypeObject */, 242, offsetof (DDS_XTypes_TypeObject, _u.complete),
  DDS_OP_JEQ | DDS_OP_TYPE_UNI | 65490 /* MinimalTypeObject */, 241, offsetof (DDS_XTypes_TypeObject, _u.minimal),
  DDS_OP_RTS,

  /* TypeIdentfierWithSize */
  DDS_OP_DLC,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_TypeIdentfierWithSize, type_id), (3u << 16u) + 64622u /* TypeIdentifier */,
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (DDS_XTypes_TypeIdentfierWithSize, typeobject_serialized_size),
  DDS_OP_RTS,

  /* TypeIdentifierWithDependencies */
  DDS_OP_DLC,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_TypeIdentifierWithDependencies, typeid_with_size), (3u << 16u) + 65528u /* TypeIdentfierWithSize */,
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (DDS_XTypes_TypeIdentifierWithDependencies, dependent_typeid_count),
  DDS_OP_ADR | DDS_OP_TYPE_SEQ | DDS_OP_SUBTYPE_STU, offsetof (DDS_XTypes_TypeIdentifierWithDependencies, dependent_typeids), sizeof (DDS_XTypes_TypeIdentfierWithSize), (4u << 16u) + 65523u /* TypeIdentfierWithSize */,
  DDS_OP_RTS
};

const dds_topic_descriptor_t DDS_XTypes_TypeIdentifier_desc =
{
  sizeof (DDS_XTypes_TypeIdentifier),
  8u,
  DDS_TOPIC_NO_OPTIMIZE | DDS_TOPIC_CONTAINS_UNION,
  0u,
  "DDS::XTypes::TypeIdentifier",
  NULL,
  395,
  DDS_XTypes_TypeIdentifier_ops,
  "",
  { .data = NULL, .sz = 0u },
  { .data = NULL, .sz = 0u },
};
static const uint32_t DDS_XTypes_TypeObject_ops [] =
{
  /* TypeObject */
  DDS_OP_DLC,
  DDS_OP_ADR | DDS_OP_TYPE_UNI | DDS_OP_SUBTYPE_1BY, offsetof (DDS_XTypes_TypeObject, _d), 2u, (10u << 16u) + 4u,
  DDS_OP_JEQ | DDS_OP_TYPE_UNI | 7 /* CompleteTypeObject */, 242, offsetof (DDS_XTypes_TypeObject, _u.complete),
  DDS_OP_JEQ | DDS_OP_TYPE_UNI | 636 /* MinimalTypeObject */, 241, offsetof (DDS_XTypes_TypeObject, _u.minimal),
  DDS_OP_RTS,

  /* CompleteTypeObject */
  DDS_OP_ADR | DDS_OP_TYPE_UNI | DDS_OP_SUBTYPE_1BY, offsetof (DDS_XTypes_CompleteTypeObject, _d), 11u, (37u << 16u) + 4u,
  DDS_OP_JEQ | DDS_OP_TYPE_STU | 34 /* CompleteAliasType */, 48, offsetof (DDS_XTypes_CompleteTypeObject, _u.alias_type),
  DDS_OP_JEQ | DDS_OP_TYPE_STU | 322 /* CompleteAnnotationType */, 80, offsetof (DDS_XTypes_CompleteTypeObject, _u.annotation_type),
  DDS_OP_JEQ | DDS_OP_TYPE_STU | 351 /* CompleteStructType */, 81, offsetof (DDS_XTypes_CompleteTypeObject, _u.struct_type),
  DDS_OP_JEQ | DDS_OP_TYPE_STU | 393 /* CompleteUnionType */, 82, offsetof (DDS_XTypes_CompleteTypeObject, _u.union_type),
  DDS_OP_JEQ | DDS_OP_TYPE_STU | 444 /* CompleteBitsetType */, 83, offsetof (DDS_XTypes_CompleteTypeObject, _u.bitset_type),
  DDS_OP_JEQ | DDS_OP_TYPE_STU | 474 /* CompleteSequenceType */, 96, offsetof (DDS_XTypes_CompleteTypeObject, _u.sequence_type),
  DDS_OP_JEQ | DDS_OP_TYPE_STU | 513 /* CompleteArrayType */, 97, offsetof (DDS_XTypes_CompleteTypeObject, _u.array_type),
  DDS_OP_JEQ | DDS_OP_TYPE_STU | 531 /* CompleteMapType */, 98, offsetof (DDS_XTypes_CompleteTypeObject, _u.map_type),
  DDS_OP_JEQ | DDS_OP_TYPE_STU | 540 /* CompleteEnumeratedType */, 64, offsetof (DDS_XTypes_CompleteTypeObject, _u.enumerated_type),
  DDS_OP_JEQ | DDS_OP_TYPE_STU | 572 /* CompleteBitmaskType */, 65, offsetof (DDS_XTypes_CompleteTypeObject, _u.bitmask_type),
  DDS_OP_JEQ | DDS_OP_TYPE_STU | 596 /* CompleteExtendedType */, 0, offsetof (DDS_XTypes_CompleteTypeObject, _u.extended_type),
  DDS_OP_RTS,

  /* CompleteAliasType */
  DDS_OP_ADR | DDS_OP_TYPE_2BY, offsetof (DDS_XTypes_CompleteAliasType, alias_flags),
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_CompleteAliasType, header), (3u << 16u) + 7u /* CompleteAliasHeader */,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_CompleteAliasType, body), (3u << 16u) + 256u /* CompleteAliasBody */,
  DDS_OP_RTS,

  /* CompleteAliasHeader */
  DDS_OP_DLC,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_CompleteAliasHeader, detail), (3u << 16u) + 4u /* CompleteTypeDetail */,
  DDS_OP_RTS,

  /* CompleteTypeDetail */
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_CompleteTypeDetail, ann_builtin), (3u << 16u) + 11u /* AppliedBuiltinTypeAnnotations */,
  DDS_OP_ADR | DDS_OP_TYPE_SEQ | DDS_OP_SUBTYPE_STU, offsetof (DDS_XTypes_CompleteTypeDetail, ann_custom), sizeof (DDS_XTypes_AppliedAnnotation), (4u << 16u) + 22u /* AppliedAnnotation */,
  DDS_OP_ADR | DDS_OP_TYPE_BST, offsetof (DDS_XTypes_CompleteTypeDetail, type_name), 257u,
  DDS_OP_RTS,

  /* AppliedBuiltinTypeAnnotations */
  DDS_OP_DLC,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_AppliedBuiltinTypeAnnotations, verbatim), (3u << 16u) + 4u /* AppliedVerbatimAnnotation */,
  DDS_OP_RTS,

  /* AppliedVerbatimAnnotation */
  DDS_OP_ADR | DDS_OP_TYPE_BST, offsetof (DDS_XTypes_AppliedVerbatimAnnotation, placement), 33u,
  DDS_OP_ADR | DDS_OP_TYPE_BST, offsetof (DDS_XTypes_AppliedVerbatimAnnotation, language), 33u,
  DDS_OP_ADR | DDS_OP_TYPE_STR, offsetof (DDS_XTypes_AppliedVerbatimAnnotation, text),
  DDS_OP_RTS,

  /* AppliedAnnotation */
  DDS_OP_DLC,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_AppliedAnnotation, annotation_typeid), (3u << 16u) + 8u /* TypeIdentifier */,
  DDS_OP_ADR | DDS_OP_TYPE_SEQ | DDS_OP_SUBTYPE_STU, offsetof (DDS_XTypes_AppliedAnnotation, param_seq), sizeof (DDS_XTypes_AppliedAnnotationParameter), (4u << 16u) + 157u /* AppliedAnnotationParameter */,
  DDS_OP_RTS,

  /* TypeIdentifier */
  DDS_OP_ADR | DDS_OP_TYPE_UNI | DDS_OP_SUBTYPE_1BY, offsetof (DDS_XTypes_TypeIdentifier, _d), 14u, (50u << 16u) + 4u,
  DDS_OP_JEQ | DDS_OP_TYPE_STU | 47 /* StringSTypeDefn */, 112, offsetof (DDS_XTypes_TypeIdentifier, _u.string_sdefn),
  DDS_OP_JEQ | DDS_OP_TYPE_STU | 44 /* StringSTypeDefn */, 114, offsetof (DDS_XTypes_TypeIdentifier, _u.string_sdefn),
  DDS_OP_JEQ | DDS_OP_TYPE_STU | 44 /* StringLTypeDefn */, 113, offsetof (DDS_XTypes_TypeIdentifier, _u.string_ldefn),
  DDS_OP_JEQ | DDS_OP_TYPE_STU | 41 /* StringLTypeDefn */, 115, offsetof (DDS_XTypes_TypeIdentifier, _u.string_ldefn),
  DDS_OP_JEQ | DDS_OP_TYPE_STU | 41 /* PlainSequenceSElemDefn */, 128, offsetof (DDS_XTypes_TypeIdentifier, _u.seq_sdefn),
  DDS_OP_JEQ | DDS_OP_TYPE_STU | 52 /* PlainSequenceLElemDefn */, 129, offsetof (DDS_XTypes_TypeIdentifier, _u.seq_ldefn),
  DDS_OP_JEQ | DDS_OP_TYPE_STU | 58 /* PlainArraySElemDefn */, 144, offsetof (DDS_XTypes_TypeIdentifier, _u.array_sdefn),
  DDS_OP_JEQ | DDS_OP_TYPE_STU | 64 /* PlainArrayLElemDefn */, 145, offsetof (DDS_XTypes_TypeIdentifier, _u.array_ldefn),
  DDS_OP_JEQ | DDS_OP_TYPE_STU | 70 /* PlainMapSTypeDefn */, 160, offsetof (DDS_XTypes_TypeIdentifier, _u.map_sdefn),
  DDS_OP_JEQ | DDS_OP_TYPE_STU | 81 /* PlainMapLTypeDefn */, 161, offsetof (DDS_XTypes_TypeIdentifier, _u.map_ldefn),
  DDS_OP_JEQ | DDS_OP_TYPE_STU | 92 /* StronglyConnectedComponentId */, 176, offsetof (DDS_XTypes_TypeIdentifier, _u.sc_component_id),
  DDS_OP_JEQ | DDS_OP_TYPE_ARR | 9, 242, offsetof (DDS_XTypes_TypeIdentifier, _u.equivalence_hash),
  DDS_OP_JEQ | DDS_OP_TYPE_ARR | 6, 241, offsetof (DDS_XTypes_TypeIdentifier, _u.equivalence_hash),
  DDS_OP_JEQ | DDS_OP_TYPE_STU | 107 /* ExtendedTypeDefn */, 0, offsetof (DDS_XTypes_TypeIdentifier, _u.extended_defn),
  DDS_OP_ADR | DDS_OP_TYPE_ARR | DDS_OP_SUBTYPE_1BY, 0u, 14u,
  DDS_OP_RTS,
  DDS_OP_RTS,

  /* StringSTypeDefn */
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (DDS_XTypes_StringSTypeDefn, bound),
  DDS_OP_RTS,

  /* StringLTypeDefn */
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (DDS_XTypes_StringLTypeDefn, bound),
  DDS_OP_RTS,

  /* PlainSequenceSElemDefn */
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_PlainSequenceSElemDefn, header), (3u << 16u) + 9u /* PlainCollectionHeader */,
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (DDS_XTypes_PlainSequenceSElemDefn, bound),
  DDS_OP_ADR | DDS_OP_TYPE_EXT | DDS_OP_FLAG_EXT, offsetof (DDS_XTypes_PlainSequenceSElemDefn, element_identifier), (3u << 16u) + 65474u /* TypeIdentifier */,
  DDS_OP_RTS,

  /* PlainCollectionHeader */
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (DDS_XTypes_PlainCollectionHeader, equiv_kind),
  DDS_OP_ADR | DDS_OP_TYPE_2BY, offsetof (DDS_XTypes_PlainCollectionHeader, element_flags),
  DDS_OP_RTS,

  /* PlainSequenceLElemDefn */
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_PlainSequenceLElemDefn, header), (3u << 16u) + 65531u /* PlainCollectionHeader */,
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (DDS_XTypes_PlainSequenceLElemDefn, bound),
  DDS_OP_ADR | DDS_OP_TYPE_EXT | DDS_OP_FLAG_EXT, offsetof (DDS_XTypes_PlainSequenceLElemDefn, element_identifier), (3u << 16u) + 65460u /* TypeIdentifier */,
  DDS_OP_RTS,

  /* PlainArraySElemDefn */
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_PlainArraySElemDefn, header), (3u << 16u) + 65522u /* PlainCollectionHeader */,
  DDS_OP_ADR | DDS_OP_TYPE_SEQ | DDS_OP_SUBTYPE_1BY, offsetof (DDS_XTypes_PlainArraySElemDefn, array_bound_seq),
  DDS_OP_ADR | DDS_OP_TYPE_EXT | DDS_OP_FLAG_EXT, offsetof (DDS_XTypes_PlainArraySElemDefn, element_identifier), (3u << 16u) + 65451u /* TypeIdentifier */,
  DDS_OP_RTS,

  /* PlainArrayLElemDefn */
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_PlainArrayLElemDefn, header), (3u << 16u) + 65513u /* PlainCollectionHeader */,
  DDS_OP_ADR | DDS_OP_TYPE_SEQ | DDS_OP_SUBTYPE_4BY, offsetof (DDS_XTypes_PlainArrayLElemDefn, array_bound_seq),
  DDS_OP_ADR | DDS_OP_TYPE_EXT | DDS_OP_FLAG_EXT, offsetof (DDS_XTypes_PlainArrayLElemDefn, element_identifier), (3u << 16u) + 65442u /* TypeIdentifier */,
  DDS_OP_RTS,

  /* PlainMapSTypeDefn */
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_PlainMapSTypeDefn, header), (3u << 16u) + 65504u /* PlainCollectionHeader */,
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (DDS_XTypes_PlainMapSTypeDefn, bound),
  DDS_OP_ADR | DDS_OP_TYPE_EXT | DDS_OP_FLAG_EXT, offsetof (DDS_XTypes_PlainMapSTypeDefn, element_identifier), (3u << 16u) + 65433u /* TypeIdentifier */,
  DDS_OP_ADR | DDS_OP_TYPE_2BY, offsetof (DDS_XTypes_PlainMapSTypeDefn, key_flags),
  DDS_OP_ADR | DDS_OP_TYPE_EXT | DDS_OP_FLAG_EXT, offsetof (DDS_XTypes_PlainMapSTypeDefn, key_identifier), (3u << 16u) + 65428u /* TypeIdentifier */,
  DDS_OP_RTS,

  /* PlainMapLTypeDefn */
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_PlainMapLTypeDefn, header), (3u << 16u) + 65490u /* PlainCollectionHeader */,
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (DDS_XTypes_PlainMapLTypeDefn, bound),
  DDS_OP_ADR | DDS_OP_TYPE_EXT | DDS_OP_FLAG_EXT, offsetof (DDS_XTypes_PlainMapLTypeDefn, element_identifier), (3u << 16u) + 65419u /* TypeIdentifier */,
  DDS_OP_ADR | DDS_OP_TYPE_2BY, offsetof (DDS_XTypes_PlainMapLTypeDefn, key_flags),
  DDS_OP_ADR | DDS_OP_TYPE_EXT | DDS_OP_FLAG_EXT, offsetof (DDS_XTypes_PlainMapLTypeDefn, key_identifier), (3u << 16u) + 65414u /* TypeIdentifier */,
  DDS_OP_RTS,

  /* StronglyConnectedComponentId */
  DDS_OP_DLC,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_StronglyConnectedComponentId, sc_component_id), (3u << 16u) + 8u /* TypeObjectHashId */,
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (DDS_XTypes_StronglyConnectedComponentId, scc_length),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (DDS_XTypes_StronglyConnectedComponentId, scc_index),
  DDS_OP_RTS,

  /* TypeObjectHashId */
  DDS_OP_ADR | DDS_OP_TYPE_UNI | DDS_OP_SUBTYPE_1BY, offsetof (DDS_XTypes_TypeObjectHashId, _d), 2u, (14u << 16u) + 4u,
  DDS_OP_JEQ | DDS_OP_TYPE_ARR | 6, 242, offsetof (DDS_XTypes_TypeObjectHashId, _u.hash),
  DDS_OP_JEQ | DDS_OP_TYPE_ARR | 3, 241, offsetof (DDS_XTypes_TypeObjectHashId, _u.hash),
  DDS_OP_ADR | DDS_OP_TYPE_ARR | DDS_OP_SUBTYPE_1BY, 0u, 14u,
  DDS_OP_RTS,
  DDS_OP_RTS,

  /* ExtendedTypeDefn */
  DDS_OP_PLC,
  DDS_OP_RTS,

  /* AppliedAnnotationParameter */
  DDS_OP_DLC,
  DDS_OP_ADR | DDS_OP_TYPE_ARR | DDS_OP_SUBTYPE_1BY, offsetof (DDS_XTypes_AppliedAnnotationParameter, paramname_hash), 4u,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_AppliedAnnotationParameter, value), (3u << 16u) + 4u /* AnnotationParameterValue */,
  DDS_OP_RTS,

  /* AnnotationParameterValue */
  DDS_OP_ADR | DDS_OP_TYPE_UNI | DDS_OP_SUBTYPE_1BY, offsetof (DDS_XTypes_AnnotationParameterValue, _d), 14u, (50u << 16u) + 4u,
  DDS_OP_JEQ | DDS_OP_TYPE_1BY | 0, 1, offsetof (DDS_XTypes_AnnotationParameterValue, _u.boolean_value),
  DDS_OP_JEQ | DDS_OP_TYPE_1BY | 0, 2, offsetof (DDS_XTypes_AnnotationParameterValue, _u.byte_value),
  DDS_OP_JEQ | DDS_OP_TYPE_2BY | 0, 3, offsetof (DDS_XTypes_AnnotationParameterValue, _u.int16_value),
  DDS_OP_JEQ | DDS_OP_TYPE_2BY | 0, 6, offsetof (DDS_XTypes_AnnotationParameterValue, _u.uint_16_value),
  DDS_OP_JEQ | DDS_OP_TYPE_4BY | 0, 4, offsetof (DDS_XTypes_AnnotationParameterValue, _u.int32_value),
  DDS_OP_JEQ | DDS_OP_TYPE_4BY | 0, 7, offsetof (DDS_XTypes_AnnotationParameterValue, _u.uint32_value),
  DDS_OP_JEQ | DDS_OP_TYPE_8BY | 0, 5, offsetof (DDS_XTypes_AnnotationParameterValue, _u.int64_value),
  DDS_OP_JEQ | DDS_OP_TYPE_8BY | 0, 8, offsetof (DDS_XTypes_AnnotationParameterValue, _u.uint64_value),
  DDS_OP_JEQ | DDS_OP_TYPE_4BY | 0, 9, offsetof (DDS_XTypes_AnnotationParameterValue, _u.float32_value),
  DDS_OP_JEQ | DDS_OP_TYPE_8BY | 0, 10, offsetof (DDS_XTypes_AnnotationParameterValue, _u.float64_value),
  DDS_OP_JEQ | DDS_OP_TYPE_1BY | 0, 16, offsetof (DDS_XTypes_AnnotationParameterValue, _u.char_value),
  DDS_OP_JEQ | DDS_OP_TYPE_4BY | 0, 64, offsetof (DDS_XTypes_AnnotationParameterValue, _u.enumerated_value),
  DDS_OP_JEQ | DDS_OP_TYPE_BST | 6, 32, offsetof (DDS_XTypes_AnnotationParameterValue, _u.string8_value),
  DDS_OP_JEQ | DDS_OP_TYPE_STU | 8 /* ExtendedAnnotationParameterValue */, 0, offsetof (DDS_XTypes_AnnotationParameterValue, _u.extended_value),
  DDS_OP_ADR | DDS_OP_TYPE_BST, offsetof (DDS_XTypes_AnnotationParameterValue, _u.string8_value), 129u,
  DDS_OP_RTS,
  DDS_OP_RTS,

  /* ExtendedAnnotationParameterValue */
  DDS_OP_PLC,
  DDS_OP_RTS,

  /* CompleteAliasBody */
  DDS_OP_DLC,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_CompleteAliasBody, common), (3u << 16u) + 11u /* CommonAliasBody */,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_CompleteAliasBody, ann_builtin), (3u << 16u) + 14u /* AppliedBuiltinMemberAnnotations */,
  DDS_OP_ADR | DDS_OP_TYPE_SEQ | DDS_OP_SUBTYPE_STU, offsetof (DDS_XTypes_CompleteAliasBody, ann_custom), sizeof (DDS_XTypes_AppliedAnnotation), (4u << 16u) + 65307u /* AppliedAnnotation */,
  DDS_OP_RTS,

  /* CommonAliasBody */
  DDS_OP_ADR | DDS_OP_TYPE_2BY, offsetof (DDS_XTypes_CommonAliasBody, related_flags),
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_CommonAliasBody, related_type), (3u << 16u) + 65309u /* TypeIdentifier */,
  DDS_OP_RTS,

  /* AppliedBuiltinMemberAnnotations */
  DDS_OP_DLC,
  DDS_OP_ADR | DDS_OP_TYPE_STR, offsetof (DDS_XTypes_AppliedBuiltinMemberAnnotations, unit),
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_AppliedBuiltinMemberAnnotations, min), (3u << 16u) + 65462u /* AnnotationParameterValue */,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_AppliedBuiltinMemberAnnotations, max), (3u << 16u) + 65459u /* AnnotationParameterValue */,
  DDS_OP_ADR | DDS_OP_TYPE_STR, offsetof (DDS_XTypes_AppliedBuiltinMemberAnnotations, hash_id),
  DDS_OP_RTS,

  /* CompleteAnnotationType */
  DDS_OP_ADR | DDS_OP_TYPE_2BY, offsetof (DDS_XTypes_CompleteAnnotationType, annotation_flag),
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_CompleteAnnotationType, header), (3u << 16u) + 8u /* CompleteAnnotationHeader */,
  DDS_OP_ADR | DDS_OP_TYPE_SEQ | DDS_OP_SUBTYPE_STU, offsetof (DDS_XTypes_CompleteAnnotationType, member_seq), sizeof (DDS_XTypes_CompleteAnnotationParameter), (4u << 16u) + 10u /* CompleteAnnotationParameter */,
  DDS_OP_RTS,

  /* CompleteAnnotationHeader */
  DDS_OP_DLC,
  DDS_OP_ADR | DDS_OP_TYPE_BST, offsetof (DDS_XTypes_CompleteAnnotationHeader, annotation_name), 257u,
  DDS_OP_RTS,

  /* CompleteAnnotationParameter */
  DDS_OP_DLC,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_CompleteAnnotationParameter, common), (3u << 16u) + 10u /* CommonAnnotationParameter */,
  DDS_OP_ADR | DDS_OP_TYPE_BST, offsetof (DDS_XTypes_CompleteAnnotationParameter, name), 257u,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_CompleteAnnotationParameter, default_value), (3u << 16u) + 65431u /* AnnotationParameterValue */,
  DDS_OP_RTS,

  /* CommonAnnotationParameter */
  DDS_OP_ADR | DDS_OP_TYPE_2BY, offsetof (DDS_XTypes_CommonAnnotationParameter, member_flags),
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_CommonAnnotationParameter, member_type_id), (3u << 16u) + 65265u /* TypeIdentifier */,
  DDS_OP_RTS,

  /* CompleteStructType */
  DDS_OP_ADR | DDS_OP_TYPE_2BY, offsetof (DDS_XTypes_CompleteStructType, struct_flags),
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_CompleteStructType, header), (3u << 16u) + 8u /* CompleteStructHeader */,
  DDS_OP_ADR | DDS_OP_TYPE_SEQ | DDS_OP_SUBTYPE_STU, offsetof (DDS_XTypes_CompleteStructType, member_seq), sizeof (DDS_XTypes_CompleteStructMember), (4u << 16u) + 13u /* CompleteStructMember */,
  DDS_OP_RTS,

  /* CompleteStructHeader */
  DDS_OP_DLC,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_CompleteStructHeader, base_type), (3u << 16u) + 65250u /* TypeIdentifier */,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_CompleteStructHeader, detail), (3u << 16u) + 65213u /* CompleteTypeDetail */,
  DDS_OP_RTS,

  /* CompleteStructMember */
  DDS_OP_DLC,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_CompleteStructMember, common), (3u << 16u) + 7u /* CommonStructMember */,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_CompleteStructMember, detail), (3u << 16u) + 12u /* CompleteMemberDetail */,
  DDS_OP_RTS,

  /* CommonStructMember */
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (DDS_XTypes_CommonStructMember, member_id),
  DDS_OP_ADR | DDS_OP_TYPE_2BY, offsetof (DDS_XTypes_CommonStructMember, member_flags),
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_CommonStructMember, member_type_id), (3u << 16u) + 65231u /* TypeIdentifier */,
  DDS_OP_RTS,

  /* CompleteMemberDetail */
  DDS_OP_ADR | DDS_OP_TYPE_BST, offsetof (DDS_XTypes_CompleteMemberDetail, name), 257u,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_CompleteMemberDetail, ann_builtin), (3u << 16u) + 65455u /* AppliedBuiltinMemberAnnotations */,
  DDS_OP_ADR | DDS_OP_TYPE_SEQ | DDS_OP_SUBTYPE_STU, offsetof (DDS_XTypes_CompleteMemberDetail, ann_custom), sizeof (DDS_XTypes_AppliedAnnotation), (4u << 16u) + 65212u /* AppliedAnnotation */,
  DDS_OP_RTS,

  /* CompleteUnionType */
  DDS_OP_ADR | DDS_OP_TYPE_2BY, offsetof (DDS_XTypes_CompleteUnionType, union_flags),
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_CompleteUnionType, header), (3u << 16u) + 11u /* CompleteUnionHeader */,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_CompleteUnionType, discriminator), (3u << 16u) + 13u /* CompleteDiscriminatorMember */,
  DDS_OP_ADR | DDS_OP_TYPE_SEQ | DDS_OP_SUBTYPE_STU, offsetof (DDS_XTypes_CompleteUnionType, member_seq), sizeof (DDS_XTypes_CompleteUnionMember), (4u << 16u) + 28u /* CompleteUnionMember */,
  DDS_OP_RTS,

  /* CompleteUnionHeader */
  DDS_OP_DLC,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_CompleteUnionHeader, detail), (3u << 16u) + 65168u /* CompleteTypeDetail */,
  DDS_OP_RTS,

  /* CompleteDiscriminatorMember */
  DDS_OP_DLC,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_CompleteDiscriminatorMember, common), (3u << 16u) + 11u /* CommonDiscriminatorMember */,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_CompleteDiscriminatorMember, ann_builtin), (3u << 16u) + 65171u /* AppliedBuiltinTypeAnnotations */,
  DDS_OP_ADR | DDS_OP_TYPE_SEQ | DDS_OP_SUBTYPE_STU, offsetof (DDS_XTypes_CompleteDiscriminatorMember, ann_custom), sizeof (DDS_XTypes_AppliedAnnotation), (4u << 16u) + 65182u /* AppliedAnnotation */,
  DDS_OP_RTS,

  /* CommonDiscriminatorMember */
  DDS_OP_ADR | DDS_OP_TYPE_2BY, offsetof (DDS_XTypes_CommonDiscriminatorMember, member_flags),
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_CommonDiscriminatorMember, type_id), (3u << 16u) + 65184u /* TypeIdentifier */,
  DDS_OP_RTS,

  /* CompleteUnionMember */
  DDS_OP_DLC,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_CompleteUnionMember, common), (3u << 16u) + 7u /* CommonUnionMember */,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_CompleteUnionMember, detail), (3u << 16u) + 65485u /* CompleteMemberDetail */,
  DDS_OP_RTS,

  /* CommonUnionMember */
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (DDS_XTypes_CommonUnionMember, member_id),
  DDS_OP_ADR | DDS_OP_TYPE_2BY, offsetof (DDS_XTypes_CommonUnionMember, member_flags),
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_CommonUnionMember, type_id), (3u << 16u) + 65168u /* TypeIdentifier */,
  DDS_OP_ADR | DDS_OP_TYPE_SEQ | DDS_OP_SUBTYPE_4BY | DDS_OP_FLAG_SGN, offsetof (DDS_XTypes_CommonUnionMember, label_seq),
  DDS_OP_RTS,

  /* CompleteBitsetType */
  DDS_OP_DLC,
  DDS_OP_ADR | DDS_OP_TYPE_2BY, offsetof (DDS_XTypes_CompleteBitsetType, bitset_flags),
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_CompleteBitsetType, header), (3u << 16u) + 8u /* CompleteBitsetHeader */,
  DDS_OP_ADR | DDS_OP_TYPE_SEQ | DDS_OP_SUBTYPE_STU, offsetof (DDS_XTypes_CompleteBitsetType, field_seq), sizeof (DDS_XTypes_CompleteBitfield), (4u << 16u) + 10u /* CompleteBitfield */,
  DDS_OP_RTS,

  /* CompleteBitsetHeader */
  DDS_OP_DLC,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_CompleteBitsetHeader, detail), (3u << 16u) + 65116u /* CompleteTypeDetail */,
  DDS_OP_RTS,

  /* CompleteBitfield */
  DDS_OP_DLC,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_CompleteBitfield, common), (3u << 16u) + 7u /* CommonBitfield */,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_CompleteBitfield, detail), (3u << 16u) + 65451u /* CompleteMemberDetail */,
  DDS_OP_RTS,

  /* CommonBitfield */
  DDS_OP_ADR | DDS_OP_TYPE_2BY, offsetof (DDS_XTypes_CommonBitfield, position),
  DDS_OP_ADR | DDS_OP_TYPE_2BY, offsetof (DDS_XTypes_CommonBitfield, flags),
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (DDS_XTypes_CommonBitfield, bitcount),
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (DDS_XTypes_CommonBitfield, holder_type),
  DDS_OP_RTS,

  /* CompleteSequenceType */
  DDS_OP_ADR | DDS_OP_TYPE_2BY, offsetof (DDS_XTypes_CompleteSequenceType, collection_flag),
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_CompleteSequenceType, header), (3u << 16u) + 7u /* CompleteCollectionHeader */,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_CompleteSequenceType, element), (3u << 16u) + 15u /* CompleteCollectionElement */,
  DDS_OP_RTS,

  /* CompleteCollectionHeader */
  DDS_OP_DLC,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_CompleteCollectionHeader, common), (3u << 16u) + 7u /* CommonCollectionHeader */,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_CompleteCollectionHeader, detail), (3u << 16u) + 65082u /* CompleteTypeDetail */,
  DDS_OP_RTS,

  /* CommonCollectionHeader */
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (DDS_XTypes_CommonCollectionHeader, bound),
  DDS_OP_RTS,

  /* CompleteCollectionElement */
  DDS_OP_DLC,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_CompleteCollectionElement, common), (3u << 16u) + 7u /* CommonCollectionElement */,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_CompleteCollectionElement, detail), (3u << 16u) + 10u /* CompleteElementDetail */,
  DDS_OP_RTS,

  /* CommonCollectionElement */
  DDS_OP_ADR | DDS_OP_TYPE_2BY, offsetof (DDS_XTypes_CommonCollectionElement, element_flags),
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_CommonCollectionElement, type), (3u << 16u) + 65099u /* TypeIdentifier */,
  DDS_OP_RTS,

  /* CompleteElementDetail */
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_CompleteElementDetail, ann_builtin), (3u << 16u) + 65326u /* AppliedBuiltinMemberAnnotations */,
  DDS_OP_ADR | DDS_OP_TYPE_SEQ | DDS_OP_SUBTYPE_STU, offsetof (DDS_XTypes_CompleteElementDetail, ann_custom), sizeof (DDS_XTypes_AppliedAnnotation), (4u << 16u) + 65083u /* AppliedAnnotation */,
  DDS_OP_RTS,

  /* CompleteArrayType */
  DDS_OP_DLC,
  DDS_OP_ADR | DDS_OP_TYPE_2BY, offsetof (DDS_XTypes_CompleteArrayType, collection_flag),
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_CompleteArrayType, header), (3u << 16u) + 7u /* CompleteArrayHeader */,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_CompleteArrayType, element), (3u << 16u) + 65508u /* CompleteCollectionElement */,
  DDS_OP_RTS,

  /* CompleteArrayHeader */
  DDS_OP_DLC,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_CompleteArrayHeader, common), (3u << 16u) + 7u /* CommonArrayHeader */,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_CompleteArrayHeader, detail), (3u << 16u) + 65039u /* CompleteTypeDetail */,
  DDS_OP_RTS,

  /* CommonArrayHeader */
  DDS_OP_ADR | DDS_OP_TYPE_SEQ | DDS_OP_SUBTYPE_4BY, offsetof (DDS_XTypes_CommonArrayHeader, bound_seq),
  DDS_OP_RTS,

  /* CompleteMapType */
  DDS_OP_ADR | DDS_OP_TYPE_2BY, offsetof (DDS_XTypes_CompleteMapType, collection_flag),
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_CompleteMapType, header), (3u << 16u) + 65480u /* CompleteCollectionHeader */,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_CompleteMapType, key), (3u << 16u) + 65488u /* CompleteCollectionElement */,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_CompleteMapType, element), (3u << 16u) + 65485u /* CompleteCollectionElement */,
  DDS_OP_RTS,

  /* CompleteEnumeratedType */
  DDS_OP_ADR | DDS_OP_TYPE_2BY, offsetof (DDS_XTypes_CompleteEnumeratedType, enum_flags),
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_CompleteEnumeratedType, header), (3u << 16u) + 8u /* CompleteEnumeratedHeader */,
  DDS_OP_ADR | DDS_OP_TYPE_SEQ | DDS_OP_SUBTYPE_STU, offsetof (DDS_XTypes_CompleteEnumeratedType, literal_seq), sizeof (DDS_XTypes_CompleteEnumeratedLiteral), (4u << 16u) + 16u /* CompleteEnumeratedLiteral */,
  DDS_OP_RTS,

  /* CompleteEnumeratedHeader */
  DDS_OP_DLC,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_CompleteEnumeratedHeader, common), (3u << 16u) + 7u /* CommonEnumeratedHeader */,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_CompleteEnumeratedHeader, detail), (3u << 16u) + 65006u /* CompleteTypeDetail */,
  DDS_OP_RTS,

  /* CommonEnumeratedHeader */
  DDS_OP_ADR | DDS_OP_TYPE_2BY, offsetof (DDS_XTypes_CommonEnumeratedHeader, bit_bound),
  DDS_OP_RTS,

  /* CompleteEnumeratedLiteral */
  DDS_OP_DLC,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_CompleteEnumeratedLiteral, common), (3u << 16u) + 7u /* CommonEnumeratedLiteral */,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_CompleteEnumeratedLiteral, detail), (3u << 16u) + 65338u /* CompleteMemberDetail */,
  DDS_OP_RTS,

  /* CommonEnumeratedLiteral */
  DDS_OP_DLC,
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (DDS_XTypes_CommonEnumeratedLiteral, value),
  DDS_OP_ADR | DDS_OP_TYPE_2BY, offsetof (DDS_XTypes_CommonEnumeratedLiteral, flags),
  DDS_OP_RTS,

  /* CompleteBitmaskType */
  DDS_OP_DLC,
  DDS_OP_ADR | DDS_OP_TYPE_2BY, offsetof (DDS_XTypes_CompleteBitmaskType, bitmask_flags),
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_CompleteBitmaskType, header), (3u << 16u) + 65508u /* CompleteEnumeratedHeader */,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, 0u, (3u << 16u) + 65505u /* CompleteEnumeratedHeader */,
  DDS_OP_ADR | DDS_OP_TYPE_SEQ | DDS_OP_SUBTYPE_STU, offsetof (DDS_XTypes_CompleteBitmaskType, flag_seq), sizeof (DDS_XTypes_CompleteBitflag), (4u << 16u) + 5u /* CompleteBitflag */,
  DDS_OP_RTS,

  /* CompleteBitflag */
  DDS_OP_DLC,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_CompleteBitflag, common), (3u << 16u) + 7u /* CommonBitflag */,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_CompleteBitflag, detail), (3u << 16u) + 65310u /* CompleteMemberDetail */,
  DDS_OP_RTS,

  /* CommonBitflag */
  DDS_OP_ADR | DDS_OP_TYPE_2BY, offsetof (DDS_XTypes_CommonBitflag, position),
  DDS_OP_ADR | DDS_OP_TYPE_2BY, offsetof (DDS_XTypes_CommonBitflag, flags),
  DDS_OP_RTS,

  /* CompleteExtendedType */
  DDS_OP_PLC,
  DDS_OP_RTS,

  /* MinimalTypeObject */
  DDS_OP_ADR | DDS_OP_TYPE_UNI | DDS_OP_SUBTYPE_1BY, offsetof (DDS_XTypes_MinimalTypeObject, _d), 11u, (37u << 16u) + 4u,
  DDS_OP_JEQ | DDS_OP_TYPE_STU | 34 /* MinimalAliasType */, 48, offsetof (DDS_XTypes_MinimalTypeObject, _u.alias_type),
  DDS_OP_JEQ | DDS_OP_TYPE_STU | 47 /* MinimalAnnotationType */, 80, offsetof (DDS_XTypes_MinimalTypeObject, _u.annotation_type),
  DDS_OP_JEQ | DDS_OP_TYPE_STU | 67 /* MinimalStructType */, 81, offsetof (DDS_XTypes_MinimalTypeObject, _u.struct_type),
  DDS_OP_JEQ | DDS_OP_TYPE_STU | 95 /* MinimalUnionType */, 82, offsetof (DDS_XTypes_MinimalTypeObject, _u.union_type),
  DDS_OP_JEQ | DDS_OP_TYPE_STU | 123 /* MinimalBitsetType */, 83, offsetof (DDS_XTypes_MinimalTypeObject, _u.bitset_type),
  DDS_OP_JEQ | DDS_OP_TYPE_STU | 141 /* MinimalSequenceType */, 96, offsetof (DDS_XTypes_MinimalTypeObject, _u.sequence_type),
  DDS_OP_JEQ | DDS_OP_TYPE_STU | 157 /* MinimalArrayType */, 97, offsetof (DDS_XTypes_MinimalTypeObject, _u.array_type),
  DDS_OP_JEQ | DDS_OP_TYPE_STU | 168 /* MinimalMapType */, 98, offsetof (DDS_XTypes_MinimalTypeObject, _u.map_type),
  DDS_OP_JEQ | DDS_OP_TYPE_STU | 177 /* MinimalEnumeratedType */, 64, offsetof (DDS_XTypes_MinimalTypeObject, _u.enumerated_type),
  DDS_OP_JEQ | DDS_OP_TYPE_STU | 197 /* MinimalBitmaskType */, 65, offsetof (DDS_XTypes_MinimalTypeObject, _u.bitmask_type),
  DDS_OP_JEQ | DDS_OP_TYPE_STU | 216 /* MinimalExtendedType */, 0, offsetof (DDS_XTypes_MinimalTypeObject, _u.extended_type),
  DDS_OP_RTS,

  /* MinimalAliasType */
  DDS_OP_ADR | DDS_OP_TYPE_2BY, offsetof (DDS_XTypes_MinimalAliasType, alias_flags),
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_MinimalAliasType, header), (3u << 16u) + 7u /* MinimalAliasHeader */,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_MinimalAliasType, body), (3u << 16u) + 6u /* MinimalAliasBody */,
  DDS_OP_RTS,

  /* MinimalAliasHeader */
  DDS_OP_DLC,
  DDS_OP_RTS,

  /* MinimalAliasBody */
  DDS_OP_DLC,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_MinimalAliasBody, common), (3u << 16u) + 65165u /* CommonAliasBody */,
  DDS_OP_RTS,

  /* MinimalAnnotationType */
  DDS_OP_ADR | DDS_OP_TYPE_2BY, offsetof (DDS_XTypes_MinimalAnnotationType, annotation_flag),
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_MinimalAnnotationType, header), (3u << 16u) + 8u /* MinimalAnnotationHeader */,
  DDS_OP_ADR | DDS_OP_TYPE_SEQ | DDS_OP_SUBTYPE_STU, offsetof (DDS_XTypes_MinimalAnnotationType, member_seq), sizeof (DDS_XTypes_MinimalAnnotationParameter), (4u << 16u) + 7u /* MinimalAnnotationParameter */,
  DDS_OP_RTS,

  /* MinimalAnnotationHeader */
  DDS_OP_DLC,
  DDS_OP_RTS,

  /* MinimalAnnotationParameter */
  DDS_OP_DLC,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_MinimalAnnotationParameter, common), (3u << 16u) + 65192u /* CommonAnnotationParameter */,
  DDS_OP_ADR | DDS_OP_TYPE_ARR | DDS_OP_SUBTYPE_1BY, offsetof (DDS_XTypes_MinimalAnnotationParameter, name_hash), 4u,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_MinimalAnnotationParameter, default_value), (3u << 16u) + 65077u /* AnnotationParameterValue */,
  DDS_OP_RTS,

  /* MinimalStructType */
  DDS_OP_ADR | DDS_OP_TYPE_2BY, offsetof (DDS_XTypes_MinimalStructType, struct_flags),
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_MinimalStructType, header), (3u << 16u) + 8u /* MinimalStructHeader */,
  DDS_OP_ADR | DDS_OP_TYPE_SEQ | DDS_OP_SUBTYPE_STU, offsetof (DDS_XTypes_MinimalStructType, member_seq), sizeof (DDS_XTypes_MinimalStructMember), (4u << 16u) + 14u /* MinimalStructMember */,
  DDS_OP_RTS,

  /* MinimalStructHeader */
  DDS_OP_DLC,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_MinimalStructHeader, base_type), (3u << 16u) + 64902u /* TypeIdentifier */,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_MinimalStructHeader, detail), (3u << 16u) + 4u /* MinimalTypeDetail */,
  DDS_OP_RTS,

  /* MinimalTypeDetail */
  DDS_OP_RTS,

  /* MinimalStructMember */
  DDS_OP_DLC,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_MinimalStructMember, common), (3u << 16u) + 65194u /* CommonStructMember */,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_MinimalStructMember, detail), (3u << 16u) + 4u /* MinimalMemberDetail */,
  DDS_OP_RTS,

  /* MinimalMemberDetail */
  DDS_OP_ADR | DDS_OP_TYPE_ARR | DDS_OP_SUBTYPE_1BY, offsetof (DDS_XTypes_MinimalMemberDetail, name_hash), 4u,
  DDS_OP_RTS,

  /* MinimalUnionType */
  DDS_OP_ADR | DDS_OP_TYPE_2BY, offsetof (DDS_XTypes_MinimalUnionType, union_flags),
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_MinimalUnionType, header), (3u << 16u) + 11u /* MinimalUnionHeader */,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_MinimalUnionType, discriminator), (3u << 16u) + 13u /* MinimalDiscriminatorMember */,
  DDS_OP_ADR | DDS_OP_TYPE_SEQ | DDS_OP_SUBTYPE_STU, offsetof (DDS_XTypes_MinimalUnionType, member_seq), sizeof (DDS_XTypes_MinimalUnionMember), (4u << 16u) + 15u /* MinimalUnionMember */,
  DDS_OP_RTS,

  /* MinimalUnionHeader */
  DDS_OP_DLC,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_MinimalUnionHeader, detail), (3u << 16u) + 65509u /* MinimalTypeDetail */,
  DDS_OP_RTS,

  /* MinimalDiscriminatorMember */
  DDS_OP_DLC,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_MinimalDiscriminatorMember, common), (3u << 16u) + 65213u /* CommonDiscriminatorMember */,
  DDS_OP_RTS,

  /* MinimalUnionMember */
  DDS_OP_DLC,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_MinimalUnionMember, common), (3u << 16u) + 65222u /* CommonUnionMember */,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_MinimalUnionMember, detail), (3u << 16u) + 65505u /* MinimalMemberDetail */,
  DDS_OP_RTS,

  /* MinimalBitsetType */
  DDS_OP_DLC,
  DDS_OP_ADR | DDS_OP_TYPE_2BY, offsetof (DDS_XTypes_MinimalBitsetType, bitset_flags),
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_MinimalBitsetType, header), (3u << 16u) + 8u /* MinimalBitsetHeader */,
  DDS_OP_ADR | DDS_OP_TYPE_SEQ | DDS_OP_SUBTYPE_STU, offsetof (DDS_XTypes_MinimalBitsetType, field_seq), sizeof (DDS_XTypes_MinimalBitfield), (4u << 16u) + 7u /* MinimalBitfield */,
  DDS_OP_RTS,

  /* MinimalBitsetHeader */
  DDS_OP_DLC,
  DDS_OP_RTS,

  /* MinimalBitfield */
  DDS_OP_DLC,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_MinimalBitfield, common), (3u << 16u) + 65235u /* CommonBitfield */,
  DDS_OP_ADR | DDS_OP_TYPE_ARR | DDS_OP_SUBTYPE_1BY, offsetof (DDS_XTypes_MinimalBitfield, name_hash), 4u,
  DDS_OP_RTS,

  /* MinimalSequenceType */
  DDS_OP_ADR | DDS_OP_TYPE_2BY, offsetof (DDS_XTypes_MinimalSequenceType, collection_flag),
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_MinimalSequenceType, header), (3u << 16u) + 7u /* MinimalCollectionHeader */,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_MinimalSequenceType, element), (3u << 16u) + 9u /* MinimalCollectionElement */,
  DDS_OP_RTS,

  /* MinimalCollectionHeader */
  DDS_OP_DLC,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_MinimalCollectionHeader, common), (3u << 16u) + 65244u /* CommonCollectionHeader */,
  DDS_OP_RTS,

  /* MinimalCollectionElement */
  DDS_OP_DLC,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_MinimalCollectionElement, common), (3u << 16u) + 65250u /* CommonCollectionElement */,
  DDS_OP_RTS,

  /* MinimalArrayType */
  DDS_OP_ADR | DDS_OP_TYPE_2BY, offsetof (DDS_XTypes_MinimalArrayType, collection_flag),
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_MinimalArrayType, header), (3u << 16u) + 7u /* MinimalArrayHeader */,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_MinimalArrayType, element), (3u << 16u) + 65526u /* MinimalCollectionElement */,
  DDS_OP_RTS,

  /* MinimalArrayHeader */
  DDS_OP_DLC,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_MinimalArrayHeader, common), (3u << 16u) + 65268u /* CommonArrayHeader */,
  DDS_OP_RTS,

  /* MinimalMapType */
  DDS_OP_ADR | DDS_OP_TYPE_2BY, offsetof (DDS_XTypes_MinimalMapType, collection_flag),
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_MinimalMapType, header), (3u << 16u) + 65510u /* MinimalCollectionHeader */,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_MinimalMapType, key), (3u << 16u) + 65512u /* MinimalCollectionElement */,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_MinimalMapType, element), (3u << 16u) + 65509u /* MinimalCollectionElement */,
  DDS_OP_RTS,

  /* MinimalEnumeratedType */
  DDS_OP_ADR | DDS_OP_TYPE_2BY, offsetof (DDS_XTypes_MinimalEnumeratedType, enum_flags),
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_MinimalEnumeratedType, header), (3u << 16u) + 8u /* MinimalEnumeratedHeader */,
  DDS_OP_ADR | DDS_OP_TYPE_SEQ | DDS_OP_SUBTYPE_STU, offsetof (DDS_XTypes_MinimalEnumeratedType, literal_seq), sizeof (DDS_XTypes_MinimalEnumeratedLiteral), (4u << 16u) + 10u /* MinimalEnumeratedLiteral */,
  DDS_OP_RTS,

  /* MinimalEnumeratedHeader */
  DDS_OP_DLC,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_MinimalEnumeratedHeader, common), (3u << 16u) + 65274u /* CommonEnumeratedHeader */,
  DDS_OP_RTS,

  /* MinimalEnumeratedLiteral */
  DDS_OP_DLC,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_MinimalEnumeratedLiteral, common), (3u << 16u) + 65280u /* CommonEnumeratedLiteral */,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_MinimalEnumeratedLiteral, detail), (3u << 16u) + 65416u /* MinimalMemberDetail */,
  DDS_OP_RTS,

  /* MinimalBitmaskType */
  DDS_OP_DLC,
  DDS_OP_ADR | DDS_OP_TYPE_2BY, offsetof (DDS_XTypes_MinimalBitmaskType, bitmask_flags),
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_MinimalBitmaskType, header), (3u << 16u) + 65520u /* MinimalEnumeratedHeader */,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, 0u, (3u << 16u) + 65517u /* MinimalEnumeratedHeader */,
  DDS_OP_ADR | DDS_OP_TYPE_SEQ | DDS_OP_SUBTYPE_STU, offsetof (DDS_XTypes_MinimalBitmaskType, flag_seq), sizeof (DDS_XTypes_MinimalBitflag), (4u << 16u) + 5u /* MinimalBitflag */,
  DDS_OP_RTS,

  /* MinimalBitflag */
  DDS_OP_DLC,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_MinimalBitflag, common), (3u << 16u) + 65286u /* CommonBitflag */,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_MinimalBitflag, detail), (3u << 16u) + 65394u /* MinimalMemberDetail */,
  DDS_OP_RTS,

  /* MinimalExtendedType */
  DDS_OP_PLC,
  DDS_OP_RTS,

  /* TypeIdentfierWithSize */
  DDS_OP_DLC,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_TypeIdentfierWithSize, type_id), (3u << 16u) + 64723u /* TypeIdentifier */,
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (DDS_XTypes_TypeIdentfierWithSize, typeobject_serialized_size),
  DDS_OP_RTS,

  /* TypeIdentifierWithDependencies */
  DDS_OP_DLC,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_TypeIdentifierWithDependencies, typeid_with_size), (3u << 16u) + 65528u /* TypeIdentfierWithSize */,
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (DDS_XTypes_TypeIdentifierWithDependencies, dependent_typeid_count),
  DDS_OP_ADR | DDS_OP_TYPE_SEQ | DDS_OP_SUBTYPE_STU, offsetof (DDS_XTypes_TypeIdentifierWithDependencies, dependent_typeids), sizeof (DDS_XTypes_TypeIdentfierWithSize), (4u << 16u) + 65523u /* TypeIdentfierWithSize */,
  DDS_OP_RTS
};

const dds_topic_descriptor_t DDS_XTypes_TypeObject_desc =
{
  sizeof (DDS_XTypes_TypeObject),
  8u,
  DDS_TOPIC_NO_OPTIMIZE | DDS_TOPIC_CONTAINS_UNION,
  0u,
  "DDS::XTypes::TypeObject",
  NULL,
  393,
  DDS_XTypes_TypeObject_ops,
  "",
  { .data = NULL, .sz = 0u },
  { .data = NULL, .sz = 0u },
};
static const uint32_t DDS_XTypes_TypeInformation_ops [] =
{
  /* TypeInformation */
  DDS_OP_PLC,
  DDS_OP_JEQ | 5, 4097u,
  DDS_OP_JEQ | 7, 4098u,
  DDS_OP_RTS,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_TypeInformation, minimal), (3u << 16u) + 8u /* TypeIdentifierWithDependencies */,
  DDS_OP_RTS,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_TypeInformation, complete), (3u << 16u) + 4u /* TypeIdentifierWithDependencies */,
  DDS_OP_RTS,

  /* TypeIdentifierWithDependencies */
  DDS_OP_DLC,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_TypeIdentifierWithDependencies, typeid_with_size), (3u << 16u) + 10u /* TypeIdentfierWithSize */,
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (DDS_XTypes_TypeIdentifierWithDependencies, dependent_typeid_count),
  DDS_OP_ADR | DDS_OP_TYPE_SEQ | DDS_OP_SUBTYPE_STU, offsetof (DDS_XTypes_TypeIdentifierWithDependencies, dependent_typeids), sizeof (DDS_XTypes_TypeIdentfierWithSize), (4u << 16u) + 5u /* TypeIdentfierWithSize */,
  DDS_OP_RTS,

  /* TypeIdentfierWithSize */
  DDS_OP_DLC,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_TypeIdentfierWithSize, type_id), (3u << 16u) + 6u /* TypeIdentifier */,
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (DDS_XTypes_TypeIdentfierWithSize, typeobject_serialized_size),
  DDS_OP_RTS,

  /* TypeIdentifier */
  DDS_OP_ADR | DDS_OP_TYPE_UNI | DDS_OP_SUBTYPE_1BY, offsetof (DDS_XTypes_TypeIdentifier, _d), 14u, (50u << 16u) + 4u,
  DDS_OP_JEQ | DDS_OP_TYPE_STU | 47 /* StringSTypeDefn */, 112, offsetof (DDS_XTypes_TypeIdentifier, _u.string_sdefn),
  DDS_OP_JEQ | DDS_OP_TYPE_STU | 44 /* StringSTypeDefn */, 114, offsetof (DDS_XTypes_TypeIdentifier, _u.string_sdefn),
  DDS_OP_JEQ | DDS_OP_TYPE_STU | 44 /* StringLTypeDefn */, 113, offsetof (DDS_XTypes_TypeIdentifier, _u.string_ldefn),
  DDS_OP_JEQ | DDS_OP_TYPE_STU | 41 /* StringLTypeDefn */, 115, offsetof (DDS_XTypes_TypeIdentifier, _u.string_ldefn),
  DDS_OP_JEQ | DDS_OP_TYPE_STU | 41 /* PlainSequenceSElemDefn */, 128, offsetof (DDS_XTypes_TypeIdentifier, _u.seq_sdefn),
  DDS_OP_JEQ | DDS_OP_TYPE_STU | 52 /* PlainSequenceLElemDefn */, 129, offsetof (DDS_XTypes_TypeIdentifier, _u.seq_ldefn),
  DDS_OP_JEQ | DDS_OP_TYPE_STU | 58 /* PlainArraySElemDefn */, 144, offsetof (DDS_XTypes_TypeIdentifier, _u.array_sdefn),
  DDS_OP_JEQ | DDS_OP_TYPE_STU | 64 /* PlainArrayLElemDefn */, 145, offsetof (DDS_XTypes_TypeIdentifier, _u.array_ldefn),
  DDS_OP_JEQ | DDS_OP_TYPE_STU | 70 /* PlainMapSTypeDefn */, 160, offsetof (DDS_XTypes_TypeIdentifier, _u.map_sdefn),
  DDS_OP_JEQ | DDS_OP_TYPE_STU | 81 /* PlainMapLTypeDefn */, 161, offsetof (DDS_XTypes_TypeIdentifier, _u.map_ldefn),
  DDS_OP_JEQ | DDS_OP_TYPE_STU | 92 /* StronglyConnectedComponentId */, 176, offsetof (DDS_XTypes_TypeIdentifier, _u.sc_component_id),
  DDS_OP_JEQ | DDS_OP_TYPE_ARR | 9, 242, offsetof (DDS_XTypes_TypeIdentifier, _u.equivalence_hash),
  DDS_OP_JEQ | DDS_OP_TYPE_ARR | 6, 241, offsetof (DDS_XTypes_TypeIdentifier, _u.equivalence_hash),
  DDS_OP_JEQ | DDS_OP_TYPE_STU | 107 /* ExtendedTypeDefn */, 0, offsetof (DDS_XTypes_TypeIdentifier, _u.extended_defn),
  DDS_OP_ADR | DDS_OP_TYPE_ARR | DDS_OP_SUBTYPE_1BY, 0u, 14u,
  DDS_OP_RTS,
  DDS_OP_RTS,

  /* StringSTypeDefn */
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (DDS_XTypes_StringSTypeDefn, bound),
  DDS_OP_RTS,

  /* StringLTypeDefn */
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (DDS_XTypes_StringLTypeDefn, bound),
  DDS_OP_RTS,

  /* PlainSequenceSElemDefn */
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_PlainSequenceSElemDefn, header), (3u << 16u) + 9u /* PlainCollectionHeader */,
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (DDS_XTypes_PlainSequenceSElemDefn, bound),
  DDS_OP_ADR | DDS_OP_TYPE_EXT | DDS_OP_FLAG_EXT, offsetof (DDS_XTypes_PlainSequenceSElemDefn, element_identifier), (3u << 16u) + 65474u /* TypeIdentifier */,
  DDS_OP_RTS,

  /* PlainCollectionHeader */
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (DDS_XTypes_PlainCollectionHeader, equiv_kind),
  DDS_OP_ADR | DDS_OP_TYPE_2BY, offsetof (DDS_XTypes_PlainCollectionHeader, element_flags),
  DDS_OP_RTS,

  /* PlainSequenceLElemDefn */
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_PlainSequenceLElemDefn, header), (3u << 16u) + 65531u /* PlainCollectionHeader */,
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (DDS_XTypes_PlainSequenceLElemDefn, bound),
  DDS_OP_ADR | DDS_OP_TYPE_EXT | DDS_OP_FLAG_EXT, offsetof (DDS_XTypes_PlainSequenceLElemDefn, element_identifier), (3u << 16u) + 65460u /* TypeIdentifier */,
  DDS_OP_RTS,

  /* PlainArraySElemDefn */
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_PlainArraySElemDefn, header), (3u << 16u) + 65522u /* PlainCollectionHeader */,
  DDS_OP_ADR | DDS_OP_TYPE_SEQ | DDS_OP_SUBTYPE_1BY, offsetof (DDS_XTypes_PlainArraySElemDefn, array_bound_seq),
  DDS_OP_ADR | DDS_OP_TYPE_EXT | DDS_OP_FLAG_EXT, offsetof (DDS_XTypes_PlainArraySElemDefn, element_identifier), (3u << 16u) + 65451u /* TypeIdentifier */,
  DDS_OP_RTS,

  /* PlainArrayLElemDefn */
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_PlainArrayLElemDefn, header), (3u << 16u) + 65513u /* PlainCollectionHeader */,
  DDS_OP_ADR | DDS_OP_TYPE_SEQ | DDS_OP_SUBTYPE_4BY, offsetof (DDS_XTypes_PlainArrayLElemDefn, array_bound_seq),
  DDS_OP_ADR | DDS_OP_TYPE_EXT | DDS_OP_FLAG_EXT, offsetof (DDS_XTypes_PlainArrayLElemDefn, element_identifier), (3u << 16u) + 65442u /* TypeIdentifier */,
  DDS_OP_RTS,

  /* PlainMapSTypeDefn */
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_PlainMapSTypeDefn, header), (3u << 16u) + 65504u /* PlainCollectionHeader */,
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (DDS_XTypes_PlainMapSTypeDefn, bound),
  DDS_OP_ADR | DDS_OP_TYPE_EXT | DDS_OP_FLAG_EXT, offsetof (DDS_XTypes_PlainMapSTypeDefn, element_identifier), (3u << 16u) + 65433u /* TypeIdentifier */,
  DDS_OP_ADR | DDS_OP_TYPE_2BY, offsetof (DDS_XTypes_PlainMapSTypeDefn, key_flags),
  DDS_OP_ADR | DDS_OP_TYPE_EXT | DDS_OP_FLAG_EXT, offsetof (DDS_XTypes_PlainMapSTypeDefn, key_identifier), (3u << 16u) + 65428u /* TypeIdentifier */,
  DDS_OP_RTS,

  /* PlainMapLTypeDefn */
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_PlainMapLTypeDefn, header), (3u << 16u) + 65490u /* PlainCollectionHeader */,
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (DDS_XTypes_PlainMapLTypeDefn, bound),
  DDS_OP_ADR | DDS_OP_TYPE_EXT | DDS_OP_FLAG_EXT, offsetof (DDS_XTypes_PlainMapLTypeDefn, element_identifier), (3u << 16u) + 65419u /* TypeIdentifier */,
  DDS_OP_ADR | DDS_OP_TYPE_2BY, offsetof (DDS_XTypes_PlainMapLTypeDefn, key_flags),
  DDS_OP_ADR | DDS_OP_TYPE_EXT | DDS_OP_FLAG_EXT, offsetof (DDS_XTypes_PlainMapLTypeDefn, key_identifier), (3u << 16u) + 65414u /* TypeIdentifier */,
  DDS_OP_RTS,

  /* StronglyConnectedComponentId */
  DDS_OP_DLC,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (DDS_XTypes_StronglyConnectedComponentId, sc_component_id), (3u << 16u) + 8u /* TypeObjectHashId */,
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (DDS_XTypes_StronglyConnectedComponentId, scc_length),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (DDS_XTypes_StronglyConnectedComponentId, scc_index),
  DDS_OP_RTS,

  /* TypeObjectHashId */
  DDS_OP_ADR | DDS_OP_TYPE_UNI | DDS_OP_SUBTYPE_1BY, offsetof (DDS_XTypes_TypeObjectHashId, _d), 2u, (14u << 16u) + 4u,
  DDS_OP_JEQ | DDS_OP_TYPE_ARR | 6, 242, offsetof (DDS_XTypes_TypeObjectHashId, _u.hash),
  DDS_OP_JEQ | DDS_OP_TYPE_ARR | 3, 241, offsetof (DDS_XTypes_TypeObjectHashId, _u.hash),
  DDS_OP_ADR | DDS_OP_TYPE_ARR | DDS_OP_SUBTYPE_1BY, 0u, 14u,
  DDS_OP_RTS,
  DDS_OP_RTS,

  /* ExtendedTypeDefn */
  DDS_OP_PLC,
  DDS_OP_RTS
};

const dds_topic_descriptor_t DDS_XTypes_TypeInformation_desc =
{
  sizeof (DDS_XTypes_TypeInformation),
  sizeof (char *),
  DDS_TOPIC_NO_OPTIMIZE | DDS_TOPIC_CONTAINS_UNION,
  0u,
  "DDS::XTypes::TypeInformation",
  NULL,
  69,
  DDS_XTypes_TypeInformation_ops,
  "",
  { .data = NULL, .sz = 0u },
  { .data = NULL, .sz = 0u },
};
