/*
 * Copyright(c) 2006 to 2021 ADLINK Technology Limited and others
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v. 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0, or the Eclipse Distribution License
 * v. 1.0 which is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: EPL-2.0 OR BSD-3-Clause
 */

module XSpace {
    @bit_bound(20)
    bitmask my_bitmask {
        flag0,
        flag1
    };

    @mutable
    struct XType1 {
	    @id(1) long long_1;
	    @id(2) long long_2;
	    @id(3) long long_3;
        @id(5) my_bitmask bm_5;
    };

    @mutable
    struct XType2 {
    	@id(1) long long_1;
	    @id(2) long long_2;
	    @id(4) long long_4;
        @id(5) unsigned short bm_5;
    };
};
